SESSIONS_19_36 = [
{
 "no": 19, "module": "2", "title": "Conversion Functions and Explanation of SEE-2 / ALA of Module 2",
 "breakdown": [("Revision", "20 Min", "Discussion"),
   ("Practical 12: Conversion functions - to_char, to_date, to_number", "35 Min", "PPT, Smartboard, SQL Plus"),
   ("Practical Assignment-3: Problem solving and practice (Q26-Q50)", "50 Min", "SQL Plus"),
   ("Explanation of SEE-2 and ALA of Module 2 - student instructions for performing and submitting the work", "15 Min", "Explanation")],
 "exec": "Conversion functions are introduced through the single most common industry requirement - report formatting. Faculty shows a real salary slip and an invoice and asks students to produce exactly that output from a table using TO_CHAR with format masks (currency, comma separator, date formats). TO_DATE is taught through the classic production bug of comparing a string with a date column. The last 15 minutes are used to formally brief SEE-2 and ALA-2 with the rubric and submission timeline.",
 "sop": [
   "Step 1 (20 min): Revision of numeric, date and string functions through a 10-question rapid quiz; outcome stated - 'student will produce formatted, report-ready output and will convert safely between datatypes.'",
   "Step 2 (15 min): TO_CHAR with number masks (9,999.99, L, FM) and date masks (DD-MON-YYYY, DAY, MONTH, HH24:MI) demonstrated by reproducing a salary slip header.",
   "Step 3 (10 min): TO_DATE and TO_NUMBER demonstrated; faculty shows the ORA-01861 literal does not match format string error and corrects it.",
   "Step 4 (10 min): Practical 12 executed by students on their own data.",
   "Step 5 (50 min): Assignment-3 Q26-Q50 solved; faculty maintains a doubt register and addresses the three most repeated doubts on the board.",
   "Step 6 (15 min): SEE-2 and ALA-2 explained - problem statement, rubric, format, deadline and ERP submission steps; students note the checklist.",
   "Deliverable: A formatted report query output resembling a salary slip, Assignment-3 completed, SEE-2/ALA-2 instruction checklist noted."],
 "questions": [
   "Produce a payroll report showing employee name, joining date as '05 March 2024', and salary as 'Rs. 45,000.00' using a single query. State what will break if the server NLS settings change. (Industry reporting task)",
   "A legacy system supplies dates as the text '15/08/2024' and amounts as the text '1,25,000'. Write the queries that convert both into proper DATE and NUMBER values for insertion, and explain the error that occurs if the format mask is omitted. (Real-life integration problem)",
   "Explain with an example why WHERE join_date = '01-JAN-2024' may fail on one machine and work on another, and write the version of the condition that is safe everywhere. (Open-book, senior-level)"],
 "homework": ["Write the five TO_CHAR, TO_DATE and TO_NUMBER queries on the EMPLOYEE table as listed in the original plan; begin ALA-2 work."]
},
{
 "no": 20, "module": "2", "title": "Practice of Inbuilt Functions - Numeric, Date and String",
 "breakdown": [("Revision", "20 Min", "Discussion"),
   ("Practical 5: Practice with numeric, date and string inbuilt functions", "35 Min", "SQL Plus"),
   ("Practical Assignment-4: Problem solving and practice (Q1-Q25)", "65 Min", "SQL Plus")],
 "exec": "Dedicated practice and consolidation lab before Sessional-I. Conducted in examination mode: questions are given on a printed sheet, time is announced per question block, and no ready-made solutions are shown until each block is over. Faculty uses this session to generate a personalised weak-area list for every student, which is the basis for remedial support.",
 "sop": [
   "Step 1 (20 min): Revision of all three function families using a function-matching worksheet (requirement in column A, function in column B).",
   "Step 2 (35 min): Practical 5 executed in examination mode in three blocks of about 12 minutes; after each block the model solution is discussed for 2 minutes.",
   "Step 3 (65 min): Assignment-4 Q1-Q25 solved; faculty records for each student the question numbers attempted correctly.",
   "Step 4: Faculty prepares the weak-area list and announces remedial pairing (a strong student with a weak student) for the next lab.",
   "Deliverable: Assignment-4 solved sheet, per-student weak-area record for CCE and remedial action list."],
 "questions": [
   "From a RETAIL(bill_no, customer_name, bill_date, amount) table, produce a single report showing customer name in proper case, bill date as 'DD-MON-YYYY', amount rounded to the nearest 10 rupees and the number of days since the bill was raised. (Integrated application)",
   "A telecom company must mask customer mobile numbers so that only the last 4 digits are visible (XXXXXX1234) in a report. Write the query using string functions. (Industry problem, data privacy)",
   "Given a table of 25 employees, write one query that returns for each employee: completed years of service, salary in words-free currency format, and a flag 'Eligible'/'Not Eligible' for a bonus if service exceeds 3 years. (Open-book, multi-function)"],
 "homework": ["Complete Assignment-4 and revise Module 1 and Module 2 for Sessional-I."]
},
{
 "no": 21, "module": "2", "title": "Database Integrity Detective Challenge (Activity)",
 "breakdown": [("Provide faulty tables containing NULL values, duplicate IDs, invalid marks and missing foreign keys for data validation and error identification", "10 Min", "Instructor Briefing"),
   ("Students identify violated constraints and propose corrective actions applying NOT NULL, UNIQUE, PRIMARY KEY, FOREIGN KEY and CHECK", "70 Min", "Identifying Corrective Actions"),
   ("Students evaluate data inconsistencies and recommend solutions", "40 Min", "Evaluation")],
 "exec": "Investigation-style activity. Each team receives a deliberately corrupted schema script (duplicate roll numbers, NULL names, marks of 150 and -5, orphan foreign key rows, inconsistent department names). Teams act as 'data integrity auditors': they must detect every defect using SQL queries, document it in an audit sheet with evidence, clean the data and then alter the schema so that the defect can never recur. Faculty evaluates on detection, correction and prevention - the three-step model used in real data-quality audits.",
 "sop": [
   "Step 1 (10 min): Faculty runs the corrupted schema script on all machines, forms teams of 3-4 and distributes the audit sheet format (defect, detection query, affected rows, corrective action, preventive constraint).",
   "Step 2 (30 min): Detection phase - teams write SQL to find duplicates (GROUP BY HAVING COUNT(*)>1), NULLs, out-of-range values and orphan child rows. Minimum six defects must be found.",
   "Step 3 (25 min): Correction phase - teams clean the data using UPDATE and DELETE, keeping a record of the rows changed.",
   "Step 4 (15 min): Prevention phase - teams write and execute the ALTER statements adding the correct constraints; faculty verifies that the dirty data can no longer be re-inserted.",
   "Step 5 (30 min): Each team presents its audit sheet in 3 minutes; the class cross-questions on any defect missed.",
   "Step 6 (10 min): Faculty reveals the complete defect list, teams self-score on how many they detected, sheets submitted on ERP.",
   "Deliverable: Completed data integrity audit sheet with detection queries, corrective statements and preventive ALTER statements."],
 "questions": [
   "In the given faulty STUDENT table, write a single query to detect all duplicate enrolment numbers along with the number of occurrences, and then write the statements to retain only the earliest record of each duplicate. (Unsolved, real audit task)",
   "The RESULT table contains marks of 150 and -5 out of 100 and the client refuses to delete those rows. Propose a correction strategy acceptable to the business and implement it with SQL, then prevent recurrence. (Case-based decision)",
   "Twelve rows in ENROLMENT refer to a course_id that does not exist in COURSE. Write the query that finds them and explain in business terms what these orphan rows mean and what damage they cause in a report. (Analytical, industry-oriented)"],
 "homework": ["Submit the audit sheet on ERP; complete remaining pending assignments; prepare for Sessional-I."]
},
{
 "no": 22, "module": "1 & 2", "title": "Sessional Examination - I (Module 1 and Module 2)",
 "breakdown": [("Sessional Examination - I (Module 1 and 2) as per institute examination schedule", "120 Min", "Examination")],
 "exec": "Formal sessional examination conducted as per the institute schedule and PLM examination pattern, including application-oriented, case-based and open-book style questions drawn from the session-wise question banks of Sessions 1 to 21. Seating, invigilation and question paper handling follow the examination cell SOP.",
 "sop": [
   "Step 1: Question paper prepared jointly by all faculty teaching this subject (MCS, DPZ, YGL) to maintain a common standard, with a minimum of 50 percent application and case-based questions.",
   "Step 2: Examination conducted as per the examination cell seating plan and timing; open-book components, if any, are announced in advance with the permitted material.",
   "Step 3: Faculty invigilates and records attendance and any unfair-means case as per institute policy.",
   "Step 4: Answer sheets assessed against a common rubric prepared before evaluation so that all three faculty members mark identically.",
   "Step 5: Result shared with students, question-wise performance analysed and weak topics identified.",
   "Step 6: A remedial plan for the weak topics is announced and scheduled in the revision slots.",
   "Deliverable: Evaluated answer sheets, question-wise performance analysis and remedial plan."],
 "questions": [
   "Paper to include at least one full case-based question of the type: 'For the given hospital scenario, design the tables with appropriate constraints and write five queries required by the management.'",
   "Paper to include at least one unsolved production-situation question of the type: 'An UPDATE without a WHERE clause has been executed - describe the recovery.'",
   "Paper to include at least one open-book query-writing question based on a supplied dataset and schema diagram."],
 "homework": ["Review the evaluated answer sheet and submit a correction of every wrong answer."]
},
{
 "no": 23, "module": "3", "title": "Advanced Joins - Inner, Outer and Self Join",
 "breakdown": [("Advanced Joins: Inner, Outer, Self Join", "20 Min", "PPT, Smartboard"),
   ("Advanced Joins examples", "25 Min", "PPT, Smartboard, SQL Plus"),
   ("Displaying data from multiple tables (join)", "25 Min", "PPT, Smartboard"),
   ("Practical 1: Implement inner join, outer join (left, right, full) and self join", "15 Min", "PPT, Smartboard, SQL Plus"),
   ("Practical 2: Retrieve and display combined data from multiple tables using joins", "15 Min", "SQL Plus"),
   ("Practical Assignment-5: Problem solving and practice on joins (Q1-Q10)", "20 Min", "SQL Plus")],
 "exec": "Joins are taught with a physical activity first - two sets of cards (employees and departments) are physically matched by students on the desk to build the mental model of inner, left, right and full outer join, and the rows that remain unmatched are kept visibly aside to represent NULL-extended rows. The self join is introduced through the employee-manager relationship which exists in the students' own college hierarchy. Each join type is then written in SQL and the row counts are compared, which is the practical way to verify a join in industry.",
 "sop": [
   "Step 1 (05 min): Outcome stated - 'student will combine data from multiple related tables using the correct join type and will justify the choice of join from the business requirement.'",
   "Step 2 (20 min): Card-matching activity on the desk for inner, left, right and full outer join; students record the resulting row counts for each case.",
   "Step 3 (25 min): SQL implementation of each join type on the DEPARTMENT-EMPLOYEE schema; faculty compares row counts with the card activity to confirm the model.",
   "Step 4 (25 min): Self join demonstrated using employee-manager; faculty shows the alias requirement and the effect of using an outer self join for the top-most manager.",
   "Step 5 (30 min): Practical 1 and Practical 2 executed by students; faculty verifies that students can state, before running, how many rows the query should return.",
   "Step 6 (20 min): Assignment-5 Q1-Q10 solved.",
   "Deliverable: A join comparison table (join type, business question answered, row count obtained) and completed Practicals 1 and 2."],
 "questions": [
   "A manager asks for a report of all departments along with their employees, including departments that currently have no employees. State which join is required, write the query, and explain what the manager will do with the NULL rows. (Industry requirement)",
   "Using a SELF JOIN on EMPLOYEE(emp_id, emp_name, manager_id, salary), list every employee who earns more than his own manager. Then explain, in one line, why this result is a red flag for an HR audit. (Case-based)",
   "Two queries written by two developers on the same tables return 120 rows and 145 rows respectively. One used an INNER JOIN and the other a LEFT JOIN. Explain which rows account for the difference and how you would verify it with a single query. (Analytical, open-book)"],
 "homework": ["On DEPARTMENT and EMPLOYEE, write the five join queries (inner, left outer, departments without employees, employee-manager self join, employees earning more than their manager) given in the original plan."]
},
{
 "no": 24, "module": "3", "title": "Subqueries, Nested Queries and Correlated Subqueries, EXISTS / ANY / ALL",
 "breakdown": [("Subqueries, Nested Queries, Correlated Subqueries", "20 Min", "PPT, Smartboard"),
   ("Subqueries examples", "15 Min", "PPT, Smartboard, SQL Plus"),
   ("Retrieve data from multiple tables using subqueries (multiple, nested, correlated)", "15 Min", "SQL Plus"),
   ("SQL Queries: EXISTS, ANY, ALL", "10 Min", "PPT, Smartboard, SQL Plus"),
   ("Practical 3: Multiple-row, nested and correlated subqueries", "20 Min", "SQL Plus"),
   ("Practical 4: Solve complex SQL queries using single-row and multiple-row subqueries", "20 Min", "SQL Plus"),
   ("Practical 5: Usage of EXISTS, ANY and ALL", "20 Min", "SQL Plus")],
 "exec": "Subqueries are taught by the 'question inside a question' method - faculty writes a business question that cannot be answered in one step (employees earning more than the company average) and makes students solve it in two manual steps first, then merges the two steps into a single subquery. The correlated subquery is explained by deliberately showing the row-by-row execution using a small 5-row table so that students see why it is slower. EXISTS, ANY and ALL are compared against the equivalent IN and join forms.",
 "sop": [
   "Step 1 (05 min): Outcome stated - 'student will solve multi-step business questions using nested and correlated subqueries and will choose between IN, EXISTS and joins.'",
   "Step 2 (20 min): Two-step manual method demonstrated, then converted into a single-row subquery; rules for single-row vs multiple-row operators explained with the ORA-01427 error shown deliberately.",
   "Step 3 (15 min): Nested subquery in WHERE, FROM (inline view) and SELECT clauses demonstrated with one business example each.",
   "Step 4 (15 min): Correlated subquery traced row by row on a 5-row table on the board, then executed; performance implication discussed.",
   "Step 5 (10 min): EXISTS, ANY and ALL demonstrated and compared with the equivalent IN and join versions of the same question.",
   "Step 6 (60 min): Practicals 3, 4 and 5 executed; students must write, for each practical, the business question their query answers.",
   "Deliverable: A solved problem set in which each query is accompanied by the business question and the reason for choosing that subquery form."],
 "questions": [
   "A company wants the list of employees who earn more than the average salary of their own department. Write the correlated subquery, and then write an equivalent solution without a correlated subquery. State which you would use on a 10 lakh row table and why. (Industry performance problem)",
   "List all customers who have never placed an order, using (i) NOT EXISTS and (ii) a LEFT JOIN with IS NULL. Explain which version is safe when the order table contains NULL customer ids. (Case-based trap)",
   "Find the department whose total salary expense is the highest, without using ORDER BY and ROWNUM. Write the query using a subquery with ALL. (Unsolved, open-book)"],
 "homework": ["On DEPARTMENT and EMPLOYEE, write the five subquery questions (nested, correlated, EXISTS, ANY, ALL) given in the original plan."]
},
{
 "no": 25, "module": "3", "title": "SQL Escape Room Game - Joins and Subqueries (Activity)",
 "breakdown": [("Students solve SQL puzzles - briefing", "10 Min", "Instructor Briefing"),
   ("Level 1: INNER JOIN, Level 2: Subquery, Level 3: Correlated Subquery, Level 4: EXISTS - each correct query unlocks the next clue", "80 Min", "Puzzle solving"),
   ("Students feedback and experience sharing", "30 Min", "Experience Sharing")],
 "exec": "Gamified assessment of Module 3 querying skills. Teams of 3-4 progress through four locked levels; the output value of a correct query is the password to the next level, so a wrong query cannot be bluffed. The dataset used is a realistic e-commerce schema (CUSTOMER, ORDERS, PRODUCT, ORDER_ITEM) so that every puzzle is a genuine business question. A leaderboard is maintained on the smartboard, and the debrief converts the game into learning by discussing the fastest correct approach for each level.",
 "sop": [
   "Step 1 (10 min): Faculty loads the e-commerce dataset, forms teams, explains the unlock rule and the leaderboard, and distributes the Level-1 clue.",
   "Step 2 (15 min): Level 1 - INNER JOIN puzzle; the output value becomes the key to Level 2. Faculty verifies and hands over the next clue.",
   "Step 3 (20 min): Level 2 - subquery puzzle requiring an aggregate inside the condition.",
   "Step 4 (20 min): Level 3 - correlated subquery puzzle (per-group comparison).",
   "Step 5 (25 min): Level 4 - EXISTS / NOT EXISTS final puzzle combining three tables; first three teams to finish are recorded.",
   "Step 6 (30 min): Debrief - each level solved on the smartboard by the fastest team, alternative approaches discussed, students share what blocked them.",
   "Deliverable: Team query log of all four levels, leaderboard record and individual reflection note on the mistakes made."],
 "questions": [
   "Level-style question: identify the customer who has bought from every product category available in the store. Write the query. (Unsolved, division-type problem)",
   "Level-style question: find products that have never been ordered in the last 90 days but are still held in stock, and state the business action the company should take. (Industry case)",
   "Level-style question: for each city, display the customer with the highest total order value. Write the query and explain how you handled ties. (Open-book, senior-level)"],
 "homework": ["Submit the team query log and a written note on the two queries that took the longest and why."]
},
{
 "no": 26, "module": "3", "title": "Set Operations - UNION, INTERSECT and MINUS",
 "breakdown": [("Revision", "15 Min", "Discussion"),
   ("Set Operations: UNION, INTERSECT, MINUS", "35 Min", "PPT, Smartboard"),
   ("Executing UNION, INTERSECT, MINUS", "15 Min", "SQL Plus"),
   ("Practical 6: Implement set operators to combine results of multiple queries", "20 Min", "SQL Plus"),
   ("Practical Assignment-5: Problem solving and practice on joins (Q11-Q20)", "35 Min", "SQL Plus")],
 "exec": "Set operations are introduced through a data-migration scenario that students can visualise - merging the current and former employee registers, or finding students who appear in the admission list but not in the fee-paid list. Venn diagrams are drawn on the board and immediately mapped to the SQL. The UNION versus UNION ALL performance difference and the column-compatibility rule are stressed because both are standard examination and interview points.",
 "sop": [
   "Step 1 (15 min): Revision of joins and subqueries; outcome stated - 'student will combine and compare result sets of two queries using set operators and will distinguish them from joins.'",
   "Step 2 (20 min): Venn diagram explanation of UNION, UNION ALL, INTERSECT and MINUS with the admission list and fee-paid list example.",
   "Step 3 (15 min): Column count, datatype compatibility and ORDER BY placement rules demonstrated, including the deliberate error of mismatched columns.",
   "Step 4 (15 min): Live execution on CURRENT_EMPLOYEE and FORMER_EMPLOYEE tables; duplicate handling compared between UNION and UNION ALL with row counts.",
   "Step 5 (20 min): Practical 6 executed by students.",
   "Step 6 (35 min): Assignment-5 Q11-Q20 solved; faculty discusses one question where a set operator and a join both work and compares the two.",
   "Deliverable: A comparison sheet of UNION, UNION ALL, INTERSECT and MINUS with the row counts obtained on the live dataset."],
 "questions": [
   "A college has an ADMITTED list and a FEE_PAID list. Write queries to produce (i) all students in either list, (ii) students who have both admitted and paid, (iii) students admitted but not paid. State the business action for the third list. (Real-life case)",
   "During a data migration, the old and the new employee tables must be merged into a single report with no duplicate employee appearing twice. Write the query, and state the performance consequence if you use UNION instead of UNION ALL on 50 lakh rows. (Industry problem)",
   "Explain with an example why MINUS is not symmetric, that is, why A MINUS B is not the same as B MINUS A, and give one business question that needs each direction. (Analytical, open-book)"],
 "homework": ["On CURRENT_EMPLOYEE and FORMER_EMPLOYEE, write the five UNION, INTERSECT and MINUS queries listed in the original plan."]
},
{
 "no": 27, "module": "3", "title": "Views, Indexes, Sequences and Synonyms",
 "breakdown": [("Revision", "15 Min", "Discussion"),
   ("Views, Indexes, Sequences, Synonyms", "40 Min", "PPT, Smartboard"),
   ("Creating and using Views, Indexes, Sequences", "25 Min", "SQL Plus"),
   ("Practical 7: Creation and usage of views, indexes and sequences", "40 Min", "SQL Plus")],
 "exec": "Each object is introduced through the problem it solves rather than its syntax: a view is introduced as the answer to 'how do I let the accounts clerk see salary but not the bank account number', an index as the answer to 'why does this report take 40 seconds', a sequence as the answer to 'how do two users insert without duplicating the id'. The index portion includes a measurable demonstration - the same query is run on a large table with and without an index and the elapsed time is compared using SET TIMING ON.",
 "sop": [
   "Step 1 (15 min): Revision; outcome stated - 'student will create and justify views, indexes, sequences and synonyms for stated business needs.'",
   "Step 2 (15 min): Views - simple and complex, read-only views, WITH CHECK OPTION; faculty demonstrates column-level security by creating a restricted view and granting access.",
   "Step 3 (15 min): Indexes - creation, when an index helps and when it hurts (heavy DML tables); demonstration with SET TIMING ON on a table of at least one lakh rows generated by a script.",
   "Step 4 (10 min): Sequences - NEXTVAL and CURRVAL, use in multi-user insert, gap behaviour after rollback demonstrated live.",
   "Step 5 (10 min): Synonyms - public and private, and their role in hiding schema names from application code.",
   "Step 6 (40 min): Practical 7 executed; each student must create one view, one index with a timing comparison, one sequence used in an insert, and one synonym.",
   "Deliverable: Script file containing the four objects created, with the before-and-after timing evidence for the index."],
 "questions": [
   "The accounts clerk must see employee name, department and salary but must never see the bank account number or PAN. Implement this requirement without changing the base table, and write the GRANT statement that completes the solution. (Industry security requirement)",
   "A daily sales report takes 42 seconds on a 20 lakh row table filtered by sale_date. Propose a solution, implement it, and state one negative impact of your solution on the nightly data-load job. (Performance case study)",
   "Two data-entry operators insert invoices at the same time and both get invoice number 1007. Explain the cause and implement the correct Oracle solution. Also explain why gaps may appear in the invoice numbers and whether that is acceptable to an auditor. (Real-time problem)"],
 "homework": ["Create the EMP_DETAILS view, an index on Emp_Name, the EMP_SEQ sequence starting from 1001 and a synonym EMP, as specified in the original plan, and verify each."]
},
{
 "no": 28, "module": "3", "title": "Transaction Control Commands - COMMIT, ROLLBACK, SAVEPOINT",
 "breakdown": [("Revision", "05 Min", "Discussion"),
   ("Transaction Control Commands: COMMIT, ROLLBACK, SAVEPOINT", "30 Min", "PPT, Smartboard"),
   ("COMMIT, ROLLBACK, SAVEPOINT examples", "25 Min", "PPT, Smartboard"),
   ("Practical 8: Demonstrating transactions - COMMIT, ROLLBACK, SAVEPOINT", "20 Min", "SQL Plus"),
   ("Explanation of SEE-3 and ALA of Module 3 - student instructions", "10 Min", "Explanation"),
   ("Practical Assignment-5: Problem solving and practice on subqueries (Q1-Q10)", "30 Min", "SQL Plus")],
 "exec": "Taught through the bank fund-transfer scenario executed live by two students on two SQL*Plus sessions. One student debits account A and does not commit; the other student queries the same row from a second session and sees the old value - this demonstrates atomicity, isolation and read consistency concretely. SAVEPOINT is demonstrated through a multi-step order-booking transaction where only part of the work must be undone.",
 "sop": [
   "Step 1 (05 min): Revision; outcome stated - 'student will control transaction boundaries correctly and will explain atomicity and isolation from observed behaviour.'",
   "Step 2 (20 min): Two-session bank transfer demonstration performed by two students on the smartboard - debit without commit, read from the second session, then commit and re-read.",
   "Step 3 (15 min): COMMIT, ROLLBACK, implicit commit by DDL, and auto-commit behaviour explained from the demonstration.",
   "Step 4 (20 min): SAVEPOINT and ROLLBACK TO SAVEPOINT demonstrated through a four-step order booking where step 3 fails.",
   "Step 5 (20 min): Practical 8 executed by students in pairs so that both the transaction and the observing session are experienced.",
   "Step 6 (10 min): SEE-3 and ALA-3 explained with rubric and deadline.",
   "Step 7 (30 min): Assignment-5 subquery questions Q1-Q10 solved.",
   "Deliverable: Transaction log sheet recording the value seen by each session at each step, signed by both partners of the pair."],
 "questions": [
   "Write the complete transaction for transferring Rs. 10,000 from account A to account B including the failure case where account B does not exist. Show where COMMIT and ROLLBACK must be placed and explain what the account holder would see if the system crashed between the two UPDATE statements. (Banking scenario)",
   "A clerk made four changes, realised that the third was wrong, and does not want to lose the first two. Write the exact statement sequence using SAVEPOINT that achieves this. (Practical situation)",
   "Explain why executing a CREATE TABLE in the middle of an uncommitted transaction can make a later ROLLBACK ineffective. Demonstrate with a statement sequence. (Open-book, senior-level trap)"],
 "homework": ["On the EMPLOYEE table, perform the three SAVEPOINT, COMMIT and ROLLBACK exercises listed in the original plan and record the output of each step."]
},
{
 "no": 29, "module": "3", "title": "Introduction to Database Design, Functional Dependency and Normalization",
 "breakdown": [("Revision", "15 Min", "Discussion"),
   ("Introduction to database design", "15 Min", "PPT, Smartboard"),
   ("Functional dependency", "15 Min", "PPT, Smartboard"),
   ("Normalization: 1NF, 2NF, 3NF, BCNF", "40 Min", "PPT, Smartboard"),
   ("Comparison of 3NF and BCNF", "20 Min", "PPT, Smartboard"),
   ("Multivalued dependency: 4NF and 5NF (Project Join NF)", "15 Min", "PPT, Smartboard, SQL Plus")],
 "exec": "Normalization is taught entirely on one running real example - a single flat spreadsheet of student-course-faculty data that the college actually maintains. The same table is normalized live, one normal form per step, and after each step students are asked which specific anomaly (insert, update, delete) has just been removed. This anomaly-driven approach makes the abstract definitions usable in examination answers. BCNF is then introduced by showing a 3NF table that still has an anomaly, which is the standard examination discriminator.",
 "sop": [
   "Step 1 (15 min): Revision; outcome stated - 'student will normalize a real unnormalized table up to BCNF and will justify each decomposition by the anomaly it removes.'",
   "Step 2 (15 min): The flat STUDENT_COURSE spreadsheet is projected; students list the redundancy they can see and the three anomaly types are defined from their observations.",
   "Step 3 (15 min): Functional dependency notation introduced; students write all FDs of the projected table and identify the candidate keys.",
   "Step 4 (40 min): Live decomposition into 1NF, 2NF and 3NF; after each step faculty asks which anomaly is now impossible and students record it.",
   "Step 5 (20 min): A 3NF-but-not-BCNF example shown and decomposed; the difference is tabulated with the dependency-preservation trade-off.",
   "Step 6 (15 min): Multivalued dependency shown with the student-skill-course example and decomposed to 4NF, with a note on 5NF.",
   "Deliverable: A worksheet showing the same table at 1NF, 2NF, 3NF and BCNF with the FD list and the anomaly removed at each stage."],
 "questions": [
   "The college keeps one flat sheet: Student_ID, Student_Name, Course_ID, Course_Name, Faculty_ID, Faculty_Name, Skill. Normalize it up to 3NF, listing every functional dependency, and state one specific business problem that exists before normalization and disappears after it. (Case-based)",
   "Give a table that is in 3NF but not in BCNF from a real college or hospital context, decompose it, and state what is lost by that decomposition. (Senior-level, analytical)",
   "A manager argues that a fully normalized design makes reports slow and wants the data kept in one table. Write a reasoned response of five lines stating when denormalization is professionally acceptable and what safeguard must accompany it. (Industry judgement, open-book)"],
 "homework": ["Normalize the given STUDENT_COURSE table to 3NF, test it for BCNF, and decompose it to 4NF and 5NF as specified in the original plan."]
},
{
 "no": 30, "module": "3", "title": "Transaction Processing, ACID Properties, Backup and Recovery, Oracle Import/Export",
 "breakdown": [("Revision", "10 Min", "Discussion"),
   ("Transaction processing - introduction", "20 Min", "PPT, Smartboard"),
   ("ACID properties", "25 Min", "Video, Explanation"),
   ("Serializability of scheduling", "10 Min", "PPT, Smartboard"),
   ("Database backup and recovery", "15 Min", "PPT, Smartboard"),
   ("ORACLE Utility - Import, Export", "20 Min", "PPT, Smartboard"),
   ("Practical 9: Backup and recovery using export and import utilities", "20 Min", "SQL Plus")],
 "exec": "ACID is taught by failure demonstration: for each property the faculty shows what a system without it would do (a failed transfer leaving money nowhere for atomicity, two simultaneous bookings of the same seat for isolation). A short video reinforces concurrency. The backup portion is fully practical - students export their own schema using Data Pump, deliberately drop a table, and restore it, which gives them a genuine disaster-recovery experience.",
 "sop": [
   "Step 1 (10 min): Revision; outcome stated - 'student will explain ACID from observed failures and will perform a schema-level backup and restore.'",
   "Step 2 (20 min): Transaction states and transaction processing explained with the order-booking life cycle.",
   "Step 3 (25 min): ACID properties, each introduced by its failure scenario, supported by a short video; students write one real-world failure example per property.",
   "Step 4 (10 min): Serializability explained with a two-transaction schedule drawn on the board; students determine whether it is serializable.",
   "Step 5 (15 min): Backup types (physical, logical, full, incremental) and recovery concepts explained with the college ERP as the example.",
   "Step 6 (40 min): Practical 9 - each student performs expdp of his own schema, drops one table, and performs impdp to restore it; the restored row count must match the original.",
   "Deliverable: Export dump file, screenshot of the drop, and proof of successful restore with matching row counts."],
 "questions": [
   "Two passengers book the last seat on the same train at the same instant. Name the ACID property involved, explain what the DBMS does internally, and state what the second passenger sees. (Real-time scenario)",
   "A company's database server crashed at 3 pm; the last full backup was taken at 2 am and archive logs are available. Explain what can and cannot be recovered and outline the recovery sequence. (Industry case)",
   "Perform a logical backup of your schema, drop any one table, and restore only that table. Write every command used and state one situation in which this approach would not be sufficient. (Open-book practical)"],
 "homework": ["Watch the video links of the session uploaded on Google Classroom and submit a one-page note on any one real database failure incident and its recovery."]
},
{
 "no": 31, "module": "3", "title": "Module-3 Practice Session - Assignment-6 Problem Solving",
 "breakdown": [("Revision", "15 Min", "Discussion"),
   ("Practical Assignment-6: Problem solving and practice (Q1-Q27)", "105 Min", "SQL Plus")],
 "exec": "Extended practice lab conducted in examination mode with progressive difficulty. The 27 questions are arranged in three levels - direct joins and subqueries, multi-table analytical queries, and open-ended business questions with no single correct query. Students work individually; peer review is used for the third level so that different correct approaches are compared, which is exactly how the PLM sessional expects students to think.",
 "sop": [
   "Step 1 (15 min): Revision of joins, subqueries, set operators and views through a 10-question oral round.",
   "Step 2 (35 min): Level 1 - Q1 to Q10 solved individually in a timed block; solutions discussed for 3 minutes at the end of the block.",
   "Step 3 (35 min): Level 2 - Q11 to Q20, multi-table analytical queries; faculty circulates and records the approach used by each student.",
   "Step 4 (30 min): Level 3 - Q21 to Q27, open-ended business questions; students exchange machines and review a peer's query for correctness and efficiency.",
   "Step 5 (05 min): Faculty consolidates the best approaches seen in class and uploads them as a reference solution set.",
   "Deliverable: Assignment-6 fully solved with peer-review remarks on the Level-3 questions."],
 "questions": [
   "For an e-commerce dataset, find the top three customers by revenue in each city. Write the query and state how you would verify that the result is correct. (Analytical)",
   "Identify all products whose stock is below the average stock of their category and which have pending orders. Write the query and state the business action it triggers. (Industry problem)",
   "Write any one business question of your own that needs at least two tables and a subquery, write the query, and give it to a peer to validate. (Open-book, question-setting)"],
 "homework": ["Complete all pending assignment questions and prepare for the Module-3 activity."]
},
{
 "no": 32, "module": "3", "title": "Design, Normalize and Query - Case Study Activity",
 "breakdown": [("Form groups of 4; assign a real-world case study (Hospital Management, Library Management, College ERP) - analyse, design, identify functional dependencies, normalize up to BCNF", "20 Min", "Explanation, Definition Finalization"),
   ("Design ER Diagram", "30 Min", "Lucidchart"),
   ("Normalize up to BCNF", "20 Min", "Microsoft Word"),
   ("Write 5 SQL Queries using Joins/Subqueries", "20 Min", "SQL Plus"),
   ("Present findings", "30 Min", "Presentation")],
 "exec": "End-to-end mini project activity covering the full Module-3 cycle. Each group takes one real domain, draws the ER diagram in Lucidchart, normalizes the design up to BCNF with documented functional dependencies, implements the tables and writes five analytical queries that the management of that domain would actually ask. The deliverable is a complete design document, which is the format expected in industry and in the ALA submission.",
 "sop": [
   "Step 1 (20 min): Groups formed, domains allotted so that no two adjacent groups share a domain; faculty finalises the scope and the list of five management questions each group must answer.",
   "Step 2 (30 min): ER diagram prepared in Lucidchart with entities, attributes, keys, relationships and cardinality; faculty approves each diagram before the group proceeds.",
   "Step 3 (20 min): Normalization up to BCNF documented in Word with the FD list and the justification of each decomposition.",
   "Step 4 (20 min): Tables implemented in Oracle and the five analytical queries written using joins and subqueries, with output captured.",
   "Step 5 (30 min): Each group presents for 4 minutes - domain, ER diagram, normalization decision and one query output; other groups cross-question.",
   "Step 6: Design document uploaded on ERP as the Module-3 ALA deliverable.",
   "Deliverable: Complete design document containing ER diagram, FD list, BCNF schema, DDL script and five analytical queries with output."],
 "questions": [
   "For your allotted domain, state the five questions the management would ask the database every week and write the SQL for any three of them. (Industry-oriented)",
   "In your normalized design, identify one place where you deliberately stopped at 3NF instead of BCNF and justify the decision in business terms. (Senior-level judgement)",
   "Your ER diagram shows a many-to-many relationship. Show how it is implemented physically and write a query that uses the resulting bridge table meaningfully. (Open-book, application)"],
 "homework": ["Complete and upload the Module-3 ALA design document with all group member contributions listed."]
},
{
 "no": 33, "module": "4", "title": "Introduction to PL/SQL, Block Structure and Variables",
 "breakdown": [("Revision", "10 Min", "Discussion"),
   ("Introduction to PL/SQL", "15 Min", "PPT, Smartboard"),
   ("PL/SQL block structure", "20 Min", "PPT, Smartboard, SQL Plus"),
   ("Variables", "15 Min", "PPT, Smartboard"),
   ("Practical 1: Implement basic PL/SQL blocks", "30 Min", "SQL Plus"),
   ("Practical Assignment-7: Problem solving and practice (Q1-Q5)", "30 Min", "SQL Plus")],
 "exec": "The need for PL/SQL is established first by a problem SQL cannot solve - 'give a 10 percent raise only if the department budget allows it, otherwise 5 percent' - which requires logic. Faculty then builds the anonymous block incrementally on the smartboard: DECLARE, BEGIN, EXCEPTION, END, adding one part at a time with students typing along. Emphasis on SET SERVEROUTPUT ON, on the percent TYPE anchored declaration, and on SELECT INTO, since these three cause most beginner failures.",
 "sop": [
   "Step 1 (10 min): Revision of SQL; the conditional-raise problem posed; students attempt it in pure SQL and realise the limitation. Outcome stated - 'student will write and execute PL/SQL blocks that implement business logic.'",
   "Step 2 (15 min): Difference between SQL and PL/SQL, and the advantage of reduced network traffic explained with a diagram of 10 separate statements versus one block.",
   "Step 3 (20 min): Block structure built live - the mandatory BEGIN-END, the optional DECLARE and EXCEPTION; SET SERVEROUTPUT ON demonstrated with and without, so students recognise the silent-output problem.",
   "Step 4 (15 min): Variable declaration, constants, percent TYPE anchoring and SELECT INTO demonstrated; faculty shows the error when SELECT INTO returns more than one row.",
   "Step 5 (30 min): Practical 1 executed; every student must run at least three blocks successfully.",
   "Step 6 (30 min): Assignment-7 Q1-Q5 solved.",
   "Deliverable: Three executed PL/SQL blocks with output, including one that reads a value from a table into a variable using percent TYPE."],
 "questions": [
   "Write a PL/SQL block that fetches the salary of a given employee and prints 'High', 'Medium' or 'Low'. Then state what happens if the employee id does not exist and how you would make the block safe. (Application + anticipation of exceptions)",
   "A payroll job must apply a raise of 10 percent if the department budget is sufficient and 5 percent otherwise. Explain why this cannot be done in a single plain SQL UPDATE in a maintainable way, and write the PL/SQL block. (Industry problem)",
   "Explain the practical advantage of declaring v_name EMPLOYEE.emp_name percent TYPE instead of VARCHAR2(50), using a real maintenance scenario where the column size changes. (Open-book, senior-level)"],
 "homework": ["Write the five PL/SQL blocks on the EMPLOYEE table (welcome message, variable assignment, addition, fetch emp_name, count employees) listed in the original plan."]
},
{
 "no": 34, "module": "4", "title": "Advantages of PL/SQL, Control Structures - IF, WHILE LOOP, CASE",
 "breakdown": [("Revision", "10 Min", "Discussion"),
   ("Control structures syntax", "10 Min", "PPT, Smartboard"),
   ("Advantages of PL/SQL", "10 Min", "PPT, Smartboard"),
   ("IF statement", "15 Min", "PPT, Smartboard"),
   ("WHILE loop", "15 Min", "PPT, Smartboard"),
   ("CASE", "15 Min", "PPT, Smartboard"),
   ("Practical 2: PL/SQL programs using IF statement", "15 Min", "SQL Plus"),
   ("Practical 3: PL/SQL programs using WHILE loop", "15 Min", "SQL Plus"),
   ("Practical 4: PL/SQL programs using IF, CASE and loops", "15 Min", "SQL Plus")],
 "exec": "Control structures are taught through business rule implementation rather than number-printing exercises. IF is taught through a loan eligibility rule, CASE through a grade or bonus slab, and WHILE through an EMI schedule generation. Faculty writes the business rule in English on the board, students convert it into pseudo-code, and only then into PL/SQL - this three-step habit is what the sessional questions test.",
 "sop": [
   "Step 1 (10 min): Revision of block structure; outcome stated - 'student will implement a written business rule as a PL/SQL control structure.'",
   "Step 2 (10 min): Advantages of PL/SQL consolidated (procedural capability, error handling, reusability, performance).",
   "Step 3 (15 min): IF, IF-ELSIF-ELSE demonstrated with a loan eligibility rule given in English and converted to code by the class.",
   "Step 4 (15 min): CASE statement and CASE expression compared with IF using a bonus slab rule; difference between the two forms demonstrated in SELECT.",
   "Step 5 (15 min): WHILE LOOP demonstrated by generating a 6-month EMI schedule; faculty deliberately writes an infinite loop and shows how to detect and stop it.",
   "Step 6 (45 min): Practicals 2, 3 and 4 executed; each student must implement at least one rule given verbally by the faculty on the spot.",
   "Deliverable: Three working PL/SQL programs implementing a loan eligibility rule, a slab-based bonus and a generated EMI schedule."],
 "questions": [
   "A bank sanctions a loan if income is above 30,000 and age is below 55, sanctions with conditions if income is between 20,000 and 30,000, and rejects otherwise. Implement this as a PL/SQL block and test it with three sample applicants. (Industry rule)",
   "Generate and display a 12-month EMI schedule for a loan of Rs. 1,00,000 at 10 percent using a WHILE loop, showing month, interest, principal and closing balance. (Application-oriented)",
   "Rewrite a given four-branch IF-ELSIF block using CASE and state one situation in which CASE cannot replace IF. (Open-book, analytical)"],
 "homework": ["Write the five PL/SQL blocks using IF, WHILE and CASE on the EMPLOYEE table (salary category, even-odd, count check, salary classification, bonus category) listed in the original plan."]
},
{
 "no": 35, "module": "4", "title": "Cursors and its Types",
 "breakdown": [("Revision", "10 Min", "Discussion"),
   ("Cursors: Implicit", "15 Min", "PPT, Smartboard"),
   ("Cursors: Explicit", "15 Min", "PPT, Smartboard"),
   ("Cursors: Cursor FOR Loop", "15 Min", "PPT, Smartboard"),
   ("Cursors: Parameterized Cursor", "15 Min", "PPT, Smartboard"),
   ("Practical 5: PL/SQL programs with cursor implementation (all types)", "30 Min", "SQL Plus"),
   ("Practical Assignment-7: Problem solving and practice (Q6-Q10)", "20 Min", "SQL Plus")],
 "exec": "The need for a cursor is created by a failure first - students run a SELECT INTO that returns many rows and see the TOO_MANY_ROWS error, after which the explicit cursor is presented as the solution. Implicit cursor attributes (SQL percent ROWCOUNT, SQL percent FOUND) are demonstrated on an UPDATE, which is how they are used in real jobs. A salary-slip generation program is built end to end using a cursor FOR loop, and a parameterized cursor is used to make the same program department-wise.",
 "sop": [
   "Step 1 (10 min): Revision; faculty makes students run a multi-row SELECT INTO to produce TOO_MANY_ROWS. Outcome stated - 'student will process multiple rows row-by-row using the appropriate cursor type.'",
   "Step 2 (15 min): Implicit cursor attributes demonstrated on an UPDATE that affects several rows; students print the affected count.",
   "Step 3 (15 min): Explicit cursor - DECLARE, OPEN, FETCH, close with EXIT WHEN NOT FOUND, written step by step with the class.",
   "Step 4 (15 min): Cursor FOR loop introduced as the compact form; the same program is rewritten and the reduction in code is highlighted.",
   "Step 5 (15 min): Parameterized cursor used to generate the salary slip department-wise; the parameter is supplied at run time.",
   "Step 6 (50 min): Practical 5 and Assignment-7 Q6-Q10 executed; each student must demonstrate all four cursor forms.",
   "Deliverable: A working salary-slip generator program in all three explicit forms (basic, FOR loop, parameterized) with output."],
 "questions": [
   "Generate a department-wise salary slip listing for a department supplied at run time, using a parameterized cursor. State why a parameterized cursor is better than declaring three separate cursors. (Industry program)",
   "A batch job updated employee salaries and must log how many rows were actually changed. Write the block using implicit cursor attributes and explain where this count is used in a real production log. (Practical)",
   "Rewrite a given explicit cursor program using a cursor FOR loop and list the three statements that become unnecessary. State one case where the explicit form must still be used. (Open-book, analytical)"],
 "homework": ["Write the five cursor programs (implicit update count, explicit cursor listing, cursor FOR loop, parameterized cursor, salary filter) on the EMPLOYEE table listed in the original plan."]
},
{
 "no": 36, "module": "4", "title": "Revision of PL/SQL Block, IF, WHILE, CASE and Cursor; SEE-4 and CCE Explanation",
 "breakdown": [("Revision - PL/SQL block", "15 Min", "Discussion"),
   ("Revision - IF", "15 Min", "PPT, Smartboard"),
   ("Revision - WHILE", "15 Min", "PPT, Smartboard"),
   ("Revision - CASE", "15 Min", "PPT, Smartboard"),
   ("Revision - Cursor", "15 Min", "PPT, Smartboard"),
   ("Practical Assignment-7: Problem solving and practice (Q11-Q15)", "30 Min", "SQL Plus"),
   ("Explanation of SEE-4 and CCE of Module 4 - student instructions", "15 Min", "Explanation")],
 "exec": "Consolidation session run as a code-review clinic. Instead of re-teaching, faculty projects student-written programs collected from the previous sessions (anonymised) and the class reviews each one for correctness, efficiency and readability. Students then fix the defects on their own machines. The session ends with a formal briefing of SEE-4 and the CCE rubric for Module 4.",
 "sop": [
   "Step 1 (15 min): Rapid revision of block structure through a fill-in-the-blanks skeleton on the smartboard completed by students.",
   "Step 2 (30 min): Code review clinic - four anonymised student programs (one each on IF, WHILE, CASE and cursor) are projected; the class identifies defects and suggests corrections; faculty records the top five recurring mistakes.",
   "Step 3 (15 min): Faculty demonstrates the corrected version of the weakest program line by line.",
   "Step 4 (30 min): Assignment-7 Q11-Q15 solved individually.",
   "Step 5 (15 min): SEE-4 problem statement, CCE rubric, submission format and deadline explained; students prepare their checklist.",
   "Deliverable: Corrected versions of the reviewed programs in each student's lab file and a personal error-checklist for PL/SQL."],
 "questions": [
   "Review the given PL/SQL program (supplied in the examination) and list every logical and syntactical defect with the corrected line. (Code-review question, unsolved)",
   "Write a single PL/SQL block for a STUDENT table that classifies each student as Distinction, First Class, Pass or Fail using a cursor and CASE, and prints a class-wise count at the end. (Integrated application)",
   "A program works correctly for 10 rows but takes 4 minutes for 1 lakh rows. Give two reasons related to cursor usage and state what you would change. (Senior-level, performance)"],
 "homework": ["Write the six PL/SQL programs on the STUDENT table (fetch details, marks check, WHILE loop, result classification, cursor listing) listed in the original plan; start SEE-4 work."]
},
]
