SESSIONS_37_53 = [
{
 "no": 37, "module": "4", "title": "PL/SQL Debugging and Exception Handling Workshop (Activity)",
 "breakdown": [("Form groups of 4; provide PL/SQL programs containing logical and runtime errors - briefing", "10 Min", "Instructor Briefing"),
   ("Identify errors and classify them; implement predefined exception handlers; create user-defined exceptions for business rules", "80 Min", "Activity Execution"),
   ("Present the corrected solutions", "30 Min", "Presentation")],
 "exec": "Workshop-style activity in which each group receives a set of five broken PL/SQL programs containing compile-time errors, runtime exceptions (NO_DATA_FOUND, TOO_MANY_ROWS, ZERO_DIVIDE, VALUE_ERROR, DUP_VAL_ON_INDEX) and silent logical errors. Groups must classify each error correctly, fix it, add the right exception handler and additionally raise a user-defined exception for a business rule supplied with the program. The emphasis is on classification, because identifying the error type is what the examination and real debugging both require.",
 "sop": [
   "Step 1 (10 min): Faculty distributes the broken program set and the error classification sheet (error type, cause, fix, handler added), forms groups of 4 and allots roles - coder, reviewer, documenter, presenter.",
   "Step 2 (30 min): Groups compile each program, record the exact Oracle error number and message, and classify it as compile-time, runtime or logical.",
   "Step 3 (30 min): Groups fix the programs and attach the correct predefined exception handler to each runtime error, verifying that the program now fails gracefully.",
   "Step 4 (20 min): Groups implement a user-defined exception with RAISE and RAISE_APPLICATION_ERROR for the supplied business rule (for example salary below minimum wage).",
   "Step 5 (30 min): Each group presents one program - the original defect, the classification and the corrected code; the class verifies.",
   "Deliverable: Completed error classification sheet and five corrected, exception-safe programs uploaded on ERP."],
 "questions": [
   "The given program fails with ORA-01403 for some employee ids and works for others. Classify the error, explain the exact cause and rewrite the block so that it prints a clear business message instead of failing. (Unsolved debugging)",
   "A payroll rule states that a salary below Rs. 10,000 must never be saved. Implement this with a user-defined exception and RAISE_APPLICATION_ERROR, and explain why doing this in the database is safer than doing it only in the application form. (Industry rule)",
   "Distinguish, with one example each from the given programs, between a compile-time error, a runtime exception and a logical error that produces wrong output silently. State which is the most dangerous in production and why. (Analytical, open-book)"],
 "homework": ["Upload the corrected programs and the classification sheet; revise exception handling for the next session."]
},
{
 "no": 38, "module": "4", "title": "Exception Handling and SQL versus PL/SQL",
 "breakdown": [("Revision", "15 Min", "Discussion"),
   ("Exception handling - introduction", "15 Min", "PPT, Smartboard"),
   ("Predefined exceptions", "15 Min", "PPT, Smartboard"),
   ("User-defined exceptions", "15 Min", "PPT, Smartboard"),
   ("Handling raised exceptions", "15 Min", "PPT, Smartboard"),
   ("SQL vs PL/SQL", "15 Min", "PPT, Smartboard"),
   ("Practical 6: PL/SQL programs using exception handling", "30 Min", "SQL Plus")],
 "exec": "Formal treatment of exception handling after the practical exposure of the previous workshop, so theory follows experience. Faculty demonstrates each predefined exception by deliberately triggering it on a live table, then adds the handler and re-runs. SQLCODE and SQLERRM are introduced as the mechanism used by real applications to write error logs, and students build a small ERROR_LOG table and write their errors into it, which is standard industry practice.",
 "sop": [
   "Step 1 (15 min): Revision of the workshop findings; outcome stated - 'student will make any PL/SQL program production-safe using predefined and user-defined exception handling with error logging.'",
   "Step 2 (15 min): Exception architecture explained - declare, raise, handle; the EXCEPTION section position in the block.",
   "Step 3 (15 min): Predefined exceptions NO_DATA_FOUND, TOO_MANY_ROWS, ZERO_DIVIDE, DUP_VAL_ON_INDEX, INVALID_NUMBER triggered live one by one and then handled.",
   "Step 4 (15 min): User-defined exceptions with DECLARE, RAISE and RAISE_APPLICATION_ERROR demonstrated on a business rule.",
   "Step 5 (15 min): WHEN OTHERS with SQLCODE and SQLERRM demonstrated; students create an ERROR_LOG table and insert the error details from the handler.",
   "Step 6 (15 min): SQL vs PL/SQL compared in a tabulated form derived from the session experience.",
   "Step 7 (30 min): Practical 6 executed; every program submitted must contain a working EXCEPTION section and must log to ERROR_LOG.",
   "Deliverable: Exception-safe programs plus an ERROR_LOG table containing at least three logged error entries with code, message and timestamp."],
 "questions": [
   "Write a block that fetches an employee's salary for a given id and handles the cases of no such employee, duplicate records and any other unexpected error separately, writing each failure into an ERROR_LOG table. (Production-standard program)",
   "A block contains WHEN OTHERS THEN NULL. Explain what business risk this single line creates and rewrite it correctly. (Senior-level, real code-review issue)",
   "A banking procedure must reject a withdrawal exceeding the balance with the message 'Insufficient funds'. Implement it using a user-defined exception and state why the error number must be between -20000 and -20999. (Industry rule, open-book)"],
 "homework": ["Write the five exception-handling programs on the EMPLOYEE table (no data found, salary fetch, user-defined exception below 10,000, existence check, custom exception above 1,00,000) listed in the original plan."]
},
{
 "no": 39, "module": "4", "title": "Database Security - Authentication, Authorization, Access Control, DAC and MAC",
 "breakdown": [("Revision", "10 Min", "Discussion"),
   ("Database security: Authentication, Authorization and Access control", "30 Min", "PPT, Smartboard"),
   ("DAC (Discretionary Access Control)", "25 Min", "PPT, Smartboard"),
   ("MAC (Mandatory Access Control)", "25 Min", "PPT, Smartboard"),
   ("Practical Assignment-7: Problem solving and practice (Q16-Q20)", "30 Min", "SQL Plus")],
 "exec": "Security is taught through a role-mapping exercise on a system students know - the college ERP. Students list who can do what (student, faculty, HOD, exam cell, accounts) and the class derives authentication versus authorization from their own list. DAC is demonstrated live with GRANT between two student schemas, and MAC is explained through a defence or hospital classification example where the owner cannot decide access. A recent data-breach news item is used to show the cost of weak access control.",
 "sop": [
   "Step 1 (10 min): Revision; outcome stated - 'student will design an access control scheme for a real application and will distinguish DAC from MAC with examples.'",
   "Step 2 (15 min): Role-mapping exercise on the college ERP - students build a who-can-do-what matrix in pairs.",
   "Step 3 (15 min): Authentication, authorization and access control defined from the student matrix; a recent database breach news item is discussed for impact.",
   "Step 4 (25 min): DAC demonstrated live - two students pair up, one grants SELECT on his table to the other, the other verifies access and then access is revoked.",
   "Step 5 (25 min): MAC explained with the hospital and defence classification model; DAC, MAC and RBAC compared in a table.",
   "Step 6 (30 min): Assignment-7 Q16-Q20 solved.",
   "Deliverable: An access control matrix for the college ERP and a working DAC demonstration log between two schemas."],
 "questions": [
   "Prepare an access control matrix for a hospital database covering doctor, nurse, receptionist, lab technician and accounts, listing the tables and the operations each may perform. Identify the one role that must never have DELETE and justify it. (Case study)",
   "A clinic allows the record owner to share patient data with anyone he chooses. Explain which access control model this is, state the specific risk under medical data privacy rules, and state which model should replace it. (Industry judgement)",
   "A former employee's database account was never disabled and was used to download data after he left. Identify every control that failed and write the SQL statements that would have prevented the incident. (Real incident analysis, open-book)"],
 "homework": ["Watch the video links on database security, DAC, MAC and RBAC shared in the original plan and submit a one-page comparison note."]
},
{
 "no": 40, "module": "4", "title": "AI-Powered Database Security Audit (AI Activity)",
 "breakdown": [("Provide a Hospital or College ERP database scenario - briefing", "10 Min", "Instructor Briefing, ChatGPT, AI Assistants"),
   ("Use AI tools to suggest security policies and user roles; verify AI recommendations against database security principles; design an access-control matrix", "80 Min", "Group Formation, Execution"),
   ("Present security risks and improvements", "30 Min", "AI-assisted Research, Presentation")],
 "exec": "AI-integrated activity in which groups use ChatGPT or similar assistants to generate a security policy and role design for a hospital or college ERP, and then critically verify every AI recommendation against the principles studied in Session 39. The key learning objective is AI literacy with verification - students must mark each AI suggestion as correct, incomplete or wrong and must justify the verdict with a reason and, where possible, with an executed SQL statement.",
 "sop": [
   "Step 1 (10 min): Faculty gives the scenario and the AI-usage rules - every prompt and response must be recorded, and no recommendation may be accepted without verification.",
   "Step 2 (25 min): Groups prompt the AI tool to propose user roles, privileges and security policies for the scenario; prompts and outputs are pasted into the worksheet.",
   "Step 3 (30 min): Verification phase - each AI recommendation is marked correct, incomplete or wrong with a written justification; at least three recommendations must be tested as actual GRANT or REVOKE statements in Oracle.",
   "Step 4 (25 min): Groups design the final access-control matrix combining verified AI output with their own corrections, and list the residual security risks.",
   "Step 5 (30 min): Presentations of 4 minutes per group covering the matrix, the AI errors they caught and the improvements proposed.",
   "Deliverable: Prompt-and-response log, verification sheet with verdicts, final access control matrix and a residual risk list uploaded on ERP."],
 "questions": [
   "The AI suggested granting DBA privilege to the application user for convenience. Explain why this is unacceptable, state the specific principle violated, and write the minimum set of privileges that should be granted instead. (AI verification, industry-oriented)",
   "Design and justify the roles for a hospital ERP where a nurse may update vitals but not billing, and the accounts clerk may read billing but not diagnosis. Write the CREATE ROLE and GRANT statements. (Practical implementation)",
   "List any two security recommendations produced by the AI tool that you found incomplete, state what was missing, and give the corrected recommendation. (Critical thinking, open-book)"],
 "homework": ["Upload the AI prompt log, verification sheet and final matrix; prepare the role scripts for execution in the DCL session."]
},
{
 "no": 41, "module": "4", "title": "SQL Injection - Attack and Prevention",
 "breakdown": [("Revision", "10 Min", "Discussion"),
   ("SQL injection", "30 Min", "PPT, Smartboard"),
   ("SQL injection examples", "20 Min", "SQL Plus"),
   ("Practical Assignment-7: Problem solving and practice (Q21-Q25)", "40 Min", "SQL Plus"),
   ("Doubt solving of concept, assignment and practical questions", "20 Min", "SQL Plus")],
 "exec": "Conducted as an ethical demonstration session. Faculty builds a deliberately vulnerable login query on the smartboard, and students see the classic ' OR '1'='1 bypass succeed on a test table. The attack is then defeated in front of the class using bind variables and input validation, and the difference is shown at the generated-SQL level. Students are briefed on the legal and ethical boundary - the technique is demonstrated only on the lab test schema.",
 "sop": [
   "Step 1 (10 min): Revision of database security; ethical-use declaration explained and the outcome stated - 'student will identify an injectable query and will rewrite it securely using bind variables.'",
   "Step 2 (15 min): How a login query is built by string concatenation in application code, shown step by step.",
   "Step 3 (15 min): Live demonstration of the authentication bypass with ' OR '1'='1 and of a UNION-based data extraction on the lab test table only.",
   "Step 4 (20 min): Prevention demonstrated - bind variables, parameterised statements, input validation, least privilege and avoidance of dynamic SQL; the same attack is re-run and fails.",
   "Step 5 (40 min): Assignment-7 Q21-Q25 solved, including the rewriting of given vulnerable queries into safe ones.",
   "Step 6 (20 min): Open doubt-solving slot before the module ends.",
   "Deliverable: A before-and-after document showing one vulnerable query, the successful attack output, the secured version and proof that the attack now fails."],
 "questions": [
   "Given the query SELECT * FROM USERS WHERE username = 'input1' AND password = 'input2' built by concatenation, show the exact input that bypasses the login, explain why it works, and rewrite the query securely. (Classic unsolved industry problem)",
   "An online complaint form passes the complaint id directly into a query. Demonstrate how an attacker could read another user's complaint, and list three controls - at code level, at database privilege level and at monitoring level - that together prevent it. (Case-based, layered defence)",
   "Explain why granting the application user only SELECT, INSERT and UPDATE on specific tables limits the damage of a successful injection, and write the GRANT statements for such a least-privilege application account. (Open-book, senior-level)"],
 "questions_note": "",
 "homework": ["Write the two SQL injection questions from the original plan - demonstrate the bypass and propose the secure alternative for the given EMPLOYEE query."]
},
{
 "no": 42, "module": "4", "title": "PL/SQL Practice and Doubt Solving",
 "breakdown": [("PL/SQL programs practice", "60 Min", "SQL Plus"),
   ("Practical Assignment-7: Problem solving and practice (Q26-Q30)", "40 Min", "SQL Plus"),
   ("Doubt solving of concept, assignment and practical questions", "20 Min", "Discussion")],
 "exec": "Dedicated practice lab for Module 4 conducted in examination mode with a printed question set. Students write complete programs - including the exception section - within fixed time boxes, and faculty evaluates not only the output but also code structure and error handling, which is the standard applied in the PLM practical examination.",
 "sop": [
   "Step 1 (05 min): Printed question set distributed; evaluation standard announced - correctness 50, exception handling 20, structure and readability 20, output presentation 10.",
   "Step 2 (60 min): Programs practised in three timed blocks of 20 minutes each (control structures, cursors, exceptions); a 2-minute model discussion after each block.",
   "Step 3 (40 min): Assignment-7 Q26-Q30 solved individually.",
   "Step 4 (20 min): Open doubt-solving; faculty records the unresolved doubts and uploads written answers on ERP the same day.",
   "Deliverable: Complete Assignment-7 submission and a per-student readiness score for the Module-4 practical examination."],
 "questions": [
   "Write a complete, production-standard PL/SQL program that processes all employees of a given department, applies a slab-based increment using CASE, logs the number of rows processed, and handles the case where the department does not exist. (Integrated, examination-level)",
   "For a library system, write a block that marks a book as unavailable when issued, raises a user-defined exception if the book is already issued, and logs every failure. (Industry program)",
   "You are given a program that compiles but produces wrong totals. List the three debugging steps you would perform in order, and state what you would print at each step. (Analytical, open-book)"],
 "homework": ["Complete all pending Module-4 work and the SEE-4 submission."]
},
{
 "no": 43, "module": "4", "title": "AI-Generated Mini Project Development (AI Activity)",
 "breakdown": [("Assign a domain (Hospital, Library, Banking, College ERP) - briefing", "15 Min", "Instructor Briefing"),
   ("Use AI tools to generate database schema, PL/SQL procedures, security policies and exception handling mechanisms", "55 Min", "Activity Execution"),
   ("Validate all AI-generated content", "20 Min", "Student Skill Enhancement"),
   ("Each group demonstrates the working solution and reflects on strengths and limitations of AI assistance", "30 Min", "Presentation")],
 "exec": "Project-based AI literacy activity. Groups use an AI assistant to generate a complete small database solution for an assigned domain, then must make it actually run in Oracle - which is where AI output typically fails (non-Oracle syntax, missing semicolons, invalid datatypes, logically wrong joins). Students record every correction they had to make, and the reflection on AI limitations is itself an assessed deliverable, supporting industry readiness and AI literacy.",
 "sop": [
   "Step 1 (15 min): Domains allotted, deliverable defined (schema with at least 4 tables, 2 procedures, 1 trigger-ready rule, security policy, exception handling) and the correction log format explained.",
   "Step 2 (55 min): Groups generate the solution using AI tools, saving every prompt and output.",
   "Step 3 (20 min): Validation phase - all generated code is executed in Oracle; each error is corrected and recorded in the correction log with the reason the AI output was wrong.",
   "Step 4 (30 min): Each group demonstrates the running solution for 4 minutes and presents two strengths and two limitations of AI assistance observed first-hand.",
   "Step 5: Project files, prompt log and correction log uploaded on ERP as the Module-4 AI activity deliverable.",
   "Deliverable: A working mini database solution in Oracle, the AI prompt log and a correction log listing every AI error found and fixed."],
 "questions": [
   "The AI generated a procedure using MySQL syntax (AUTO_INCREMENT and LIMIT). Rewrite it correctly for Oracle and list every change you made. (Real AI limitation, practical)",
   "Validate the AI-generated schema for your domain against normalization rules and state at least one design flaw it contains, with the corrected design. (Analytical)",
   "State two tasks in this activity where AI assistance clearly saved time and two where it introduced errors that only domain knowledge could catch. Support each with a concrete example from your own project. (Reflection, industry readiness)"],
 "homework": ["Upload the mini project, prompt log and correction log; prepare the demonstration for evaluation."]
},
{
 "no": 44, "module": "5", "title": "Stored Procedures and Stored Functions",
 "breakdown": [("Revision", "10 Min", "PPT, Smartboard"),
   ("Stored procedures", "20 Min", "PPT, Smartboard"),
   ("Stored functions", "20 Min", "PPT, Smartboard"),
   ("Stored procedures examples", "20 Min", "SQL Plus"),
   ("Stored functions examples", "20 Min", "SQL Plus"),
   ("Practical 1: Creating stored procedures and functions", "30 Min", "SQL Plus")],
 "exec": "Introduced through the reuse problem - the same salary calculation logic written in three different programs - which students have actually experienced in earlier sessions. The procedure is then presented as named, stored, reusable logic. IN, OUT and IN OUT parameters are demonstrated with a real requirement (pass employee id, return salary and grade). The function is distinguished by the fact that it can be called inside a SELECT, which is demonstrated live and is a standard examination point.",
 "sop": [
   "Step 1 (10 min): Revision of anonymous blocks; the reuse problem posed; outcome stated - 'student will create, call and debug stored procedures and functions with correct parameter modes.'",
   "Step 2 (20 min): CREATE OR REPLACE PROCEDURE syntax, compilation, SHOW ERRORS and execution demonstrated; faculty deliberately introduces a compile error and uses SHOW ERRORS and USER_ERRORS to locate it.",
   "Step 3 (20 min): IN, OUT and IN OUT parameters demonstrated with a get-salary-and-grade requirement; calling from an anonymous block with host variables shown.",
   "Step 4 (20 min): Functions created and called from SELECT, WHERE and from a PL/SQL block; restrictions on functions used in SQL explained.",
   "Step 5 (20 min): Procedure versus function compared in a table built from the live examples.",
   "Step 6 (30 min): Practical 1 executed; each student creates at least one procedure with an OUT parameter and one function called from a SELECT.",
   "Deliverable: Two compiled database objects - one procedure with OUT parameter and one function used inside a SELECT, with execution output."],
 "questions": [
   "Create a function that returns the total salary payable for a given department, and use it inside a SELECT that lists every department with its payable amount. State why this cannot be done with a procedure. (Industry reporting requirement)",
   "A procedure must return both the employee's salary and a computed grade to the calling program. Write it with the correct parameter modes and show the calling block. (Application-oriented)",
   "A stored procedure compiled with errors and the developer cannot see why. List the exact steps and queries you would use to find the error, and state one common cause related to privileges. (Open-book, practical troubleshooting)"],
 "homework": ["Create the PRODUCT and EMPLOYEE procedures and functions listed in the original plan - display product details, increase price by 10 percent with row count, cursor listing, employee salary procedure and total salary function."]
},
{
 "no": 45, "module": "5", "title": "Stored Procedures and Stored Functions - Practice Session",
 "breakdown": [("Revision", "10 Min", "Discussion"),
   ("Practical Assignment-8: Problem solving and practice (Q1-Q20)", "110 Min", "SQL Plus")],
 "exec": "Extended hands-on lab on named program units. Students convert the anonymous blocks written in Module 4 into reusable procedures and functions, which makes the value of modularity concrete. Faculty enforces a coding standard - naming convention, parameter prefixes, mandatory exception section and a header comment - so that all three faculty members teaching this subject evaluate against the same standard.",
 "sop": [
   "Step 1 (10 min): Revision and announcement of the common coding standard (p_ for parameters, v_ for variables, mandatory header comment and EXCEPTION section).",
   "Step 2 (40 min): Q1-Q7 - conversion of earlier anonymous blocks into procedures; faculty verifies compilation and naming standard.",
   "Step 3 (40 min): Q8-Q14 - functions returning computed business values, called from SELECT statements.",
   "Step 4 (30 min): Q15-Q20 - procedures with OUT parameters and exception handling; faculty conducts a 2-question viva for each student while they work.",
   "Deliverable: A compiled script library of at least 20 procedures and functions following the common coding standard, submitted on ERP."],
 "questions": [
   "Convert any three anonymous blocks written in Module 4 into stored procedures with proper parameters and exception sections, and explain one maintenance benefit gained. (Application)",
   "Create a function that returns the number of days a library book is overdue for a given issue id, returning zero when it is not overdue, and use it in a SELECT listing all defaulters with the fine computed at Rs. 2 per day. (Industry problem)",
   "Two procedures in your library have the same name but different parameters. Explain whether Oracle allows this at schema level, and how packages change the answer. (Open-book, senior-level)"],
 "homework": ["Create the STUDENT procedure and function listed in the original plan - display student name and marks for a given id, and return average marks of all students."]
},
{
 "no": 46, "module": "5", "title": "Packages",
 "breakdown": [("Revision", "20 Min", "Discussion"),
   ("Packages", "20 Min", "PPT, Smartboard"),
   ("Packages example", "20 Min", "SQL Plus"),
   ("Practical 2: Creating and using packages", "30 Min", "SQL Plus"),
   ("Practical Assignment-8: Problem solving and practice (Q21-Q22)", "40 Min", "SQL Plus")],
 "exec": "The package is introduced as the industry answer to the script-library mess created in the previous session - 30 loose procedures with no organisation. Faculty groups the students' own procedures into a single HR_PKG with specification and body, demonstrating encapsulation, the public-private distinction and overloading. The practical benefit of a package - changing the body without invalidating dependent objects - is demonstrated live.",
 "sop": [
   "Step 1 (20 min): Revision; the loose-procedure problem shown by listing USER_OBJECTS; outcome stated - 'student will organise related program units into a package and will use public and private subprograms correctly.'",
   "Step 2 (20 min): Package specification and body explained; the specification of HR_PKG is written with the class.",
   "Step 3 (20 min): Body implemented, including one private procedure not listed in the specification, and the resulting access error is demonstrated when it is called from outside.",
   "Step 4 (10 min): Overloading demonstrated with two subprograms of the same name and different parameters; dependency advantage shown by altering the body and verifying that dependent objects stay valid.",
   "Step 5 (30 min): Practical 2 executed - each student builds a package for his own domain with at least one procedure, one function and one private subprogram.",
   "Step 6 (40 min): Assignment-8 Q21-Q22 solved.",
   "Deliverable: A compiled package with specification and body containing at least three subprograms including one private, with execution output."],
 "questions": [
   "Build a PRODUCT_PKG containing a procedure to display product details, a function returning total stock and a private procedure that writes to an audit table. Demonstrate that the private procedure cannot be called from outside the package. (Industry design)",
   "Explain, with the dependency scenario demonstrated in class, why changing a package body does not invalidate dependent objects while changing a standalone procedure can cause recompilation. (Senior-level, analytical)",
   "Design the specification only of a package that a banking application would need for account operations, listing the subprograms and their parameters, without writing the body. Justify what you kept public and what you kept private. (Open-book design task)"],
 "homework": ["Create the five PRODUCT package exercises listed in the original plan - product details procedure, total stock function, price update procedure, highest price function and the combined package."]
},
{
 "no": 47, "module": "5", "title": "Cursor Implementation - Practice Session",
 "breakdown": [("Revision", "20 Min", "Discussion"),
   ("Practical 3: Implement cursor", "40 Min", "SQL Plus"),
   ("Practical Assignment-8: Problem solving and practice (Q23-Q24)", "20 Min", "SQL Plus"),
   ("Doubt solving of concept, assignment and practical questions", "40 Min", "Discussion")],
 "exec": "Advanced cursor practice at Module-5 level, where cursors are now used inside procedures, functions and packages rather than in loose blocks. Faculty introduces cursors with FOR UPDATE and WHERE CURRENT OF, which is the pattern used in real batch-update jobs, and discusses the performance consideration of row-by-row processing versus set-based SQL - a point frequently asked at senior level.",
 "sop": [
   "Step 1 (20 min): Revision of all cursor types; outcome stated - 'student will implement cursors inside named program units and will justify row-by-row processing against set-based SQL.'",
   "Step 2 (15 min): Cursor with FOR UPDATE and WHERE CURRENT OF demonstrated on a batch salary revision.",
   "Step 3 (25 min): Practical 3 executed - students implement a cursor inside a stored procedure of their own package.",
   "Step 4 (20 min): Assignment-8 Q23-Q24 solved.",
   "Step 5 (40 min): Structured doubt-solving - students write their doubts on the board, doubts are grouped into themes and resolved theme by theme, with the solutions uploaded afterwards.",
   "Deliverable: A procedure containing a FOR UPDATE cursor performing a controlled batch update, with before-and-after data evidence."],
 "questions": [
   "Write a procedure that increases by 7 percent the salary of every employee of a given department using a cursor with FOR UPDATE and WHERE CURRENT OF, and explain what the lock protects against. (Industry batch job)",
   "The same requirement can be done by a single UPDATE statement. Compare the two approaches on correctness, performance and locking, and state when the cursor version is genuinely justified. (Senior-level comparison)",
   "A cursor-based job on 5 lakh rows takes 20 minutes and times out. Suggest two concrete changes and state the expected improvement from each. (Open-book, performance problem)"],
 "homework": ["Write the three cursor programs on the EMPLOYEE table listed in the original plan - explicit cursor listing, cursor FOR loop for the IT department and a parameterized cursor."]
},
{
 "no": 48, "module": "5", "title": "Triggers and Types of Triggers, Users - Create and Delete User",
 "breakdown": [("Revision", "10 Min", "Discussion"),
   ("Triggers introduction", "10 Min", "PPT, Smartboard"),
   ("Types of triggers", "20 Min", "PPT, Smartboard"),
   ("Users - Create user", "10 Min", "PPT, Smartboard"),
   ("Users - Delete user", "10 Min", "PPT, Smartboard"),
   ("Testing triggers: BEFORE, AFTER, INSTEAD OF (row/statement level)", "20 Min", "PPT, Smartboard"),
   ("Practical 4: Implement trigger", "20 Min", "SQL Plus"),
   ("Practical Assignment-8: Problem solving and practice (Q25-Q26)", "20 Min", "SQL Plus")],
 "exec": "Triggers are introduced through the audit requirement every organisation has - 'who changed this salary and when'. Faculty builds a salary audit trigger live, then shows it firing automatically on an UPDATE, which makes the concept of an event-driven program unit immediate. BEFORE versus AFTER and row versus statement level are demonstrated by printing messages from each, so students see the firing order. User creation is then performed practically, with each student creating a user for his own application.",
 "sop": [
   "Step 1 (10 min): Revision; the audit requirement posed; outcome stated - 'student will implement auditing and business-rule enforcement using triggers and will create and manage database users.'",
   "Step 2 (20 min): Trigger concept, firing events and the classification into BEFORE, AFTER, row-level and statement-level explained; a trigger that prints a message at each of the four points is run once to show the firing order.",
   "Step 3 (20 min): A salary audit trigger built live using :OLD and :NEW, writing to an AUDIT_SALARY table; an UPDATE is executed and the audit row is shown.",
   "Step 4 (20 min): CREATE USER, ALTER USER, DROP USER and the required CREATE SESSION privilege demonstrated; each student creates one application user.",
   "Step 5 (20 min): Practical 4 executed - each student implements one audit trigger and one rule-enforcement trigger.",
   "Step 6 (20 min): Assignment-8 Q25-Q26 solved.",
   "Deliverable: A working audit trigger with populated audit table and a created application user with login verified."],
 "questions": [
   "A company must record who changed any employee's salary, the old value, the new value and the timestamp. Implement this with a trigger and show the audit table after two updates. (Compliance requirement)",
   "A rule states that no employee record may be deleted from the EMPLOYEE table during working hours. Implement it with a trigger and state one disadvantage of enforcing such policy in a trigger rather than in the application. (Industry rule, judgement)",
   "Explain the difference between a BEFORE INSERT row-level trigger and an AFTER INSERT statement-level trigger using the firing-order output observed in class, and state which one you would use to generate a primary key value and why. (Open-book, senior-level)"],
 "homework": ["Create the three EMPLOYEE triggers listed in the original plan - BEFORE INSERT preventing salary below 10,000, AFTER UPDATE message on salary change, and BEFORE DELETE preventing deletion."]
},
{
 "no": 49, "module": "5", "title": "Revision of Stored Procedures, Functions, Packages and Triggers; SEE-5 and ALA Explanation",
 "breakdown": [("Revision - stored procedures and stored functions", "20 Min", "Discussion"),
   ("Revision - packages", "10 Min", "PPT, White Board"),
   ("Revision - trigger", "10 Min", "PPT, White Board"),
   ("Practical 5: Writing and testing triggers - BEFORE, AFTER, INSTEAD OF (row/statement level)", "30 Min", "SQL Plus"),
   ("Practical 6: Creating and managing users - CREATE and DELETE USER", "30 Min", "SQL Plus"),
   ("Explanation of SEE-5 and ALA of Module 5 - student instructions", "20 Min", "Explanation")],
 "exec": "Consolidation session for Module 5 conducted as an integration exercise - students combine their procedures, functions, package and triggers into one coherent application schema for their chosen domain and demonstrate it end to end. INSTEAD OF triggers are covered here on a complex view, which completes the trigger topic. The session closes with the formal SEE-5 and ALA-5 briefing.",
 "sop": [
   "Step 1 (40 min): Revision of procedures, functions, packages and triggers through a single integrated example built with class participation.",
   "Step 2 (30 min): Practical 5 - students write and test BEFORE, AFTER and INSTEAD OF triggers, the last one on a join-based view to demonstrate updatable views.",
   "Step 3 (30 min): Practical 6 - user creation, privilege assignment, password policy, locking and dropping of a user; each student verifies login from a second session.",
   "Step 4 (20 min): SEE-5 and ALA-5 explained - problem statement, deliverable format, rubric, deadline and ERP submission steps.",
   "Deliverable: An integrated application schema containing package, triggers and a dedicated application user, with a demonstration log."],
 "questions": [
   "A view joins EMPLOYEE and DEPARTMENT and the application needs to insert through it. Explain why a plain INSERT fails and implement the solution with an INSTEAD OF trigger. (Senior-level practical)",
   "Create an application user with the minimum privileges required to run your package and nothing more, then verify from a second session that the user cannot query the base tables directly. (Industry least-privilege task)",
   "For your domain application, list which business rules you implemented as constraints, which as triggers and which in PL/SQL procedures, and justify each placement. (Design judgement, open-book)"],
 "homework": ["Complete the ALA-5 deliverable as instructed."]
},
{
 "no": 50, "module": "5", "title": "SQL Escape Room - Advanced PL/SQL (Activity)",
 "breakdown": [("Faculty gives SQL puzzles - briefing", "15 Min", "Instructor Briefing"),
   ("Students solve SQL puzzles within a time limit; each query result unlocks the next room; the final challenge requires combining multiple SQL concepts", "90 Min", "Solve puzzles"),
   ("Students feedback", "15 Min", "Discussion")],
 "exec": "Second gamified assessment, now at Module 4-5 level. The rooms require PL/SQL rather than plain SQL - a room is unlocked by the output of a function the team must write, by the audit row produced by a trigger they must create, and by the value returned by a package subprogram. The final room is an integrated challenge combining joins, a cursor, exception handling and a trigger, closely modelled on the standard of the PLM sessional practical examination.",
 "sop": [
   "Step 1 (15 min): Faculty loads the puzzle schema, forms teams, explains the unlock mechanism and starts the timer; the leaderboard is displayed.",
   "Step 2 (20 min): Room 1 - write a function whose returned value is the key to Room 2.",
   "Step 3 (20 min): Room 2 - write a procedure with an OUT parameter and exception handling; the logged error message is the key to Room 3.",
   "Step 4 (20 min): Room 3 - create a trigger; the audit row generated is the key to Room 4.",
   "Step 5 (30 min): Room 4 - the integrated final challenge combining a multi-table query, a cursor and exception handling; completion times recorded.",
   "Step 6 (15 min): Feedback and debrief - the fastest team explains its approach, the faculty gives the model solution for every room.",
   "Deliverable: Team code log for all four rooms, leaderboard record and individual reflection on the concept that proved weakest."],
 "questions": [
   "Room-style question: write a function that returns the name of the customer with the highest total purchase in the last quarter; the returned name is your key. (Integrated application)",
   "Room-style question: create a trigger that logs every attempt to delete a product that still has pending orders, and block the deletion; the logged message is your key. (Industry rule)",
   "Final-room-style question: using a cursor, exception handling and a multi-table join, produce a defaulter report for a library with the fine computed per member, handling the case of a member with no issues. (Examination-standard integrated problem)"],
 "homework": ["Submit the team code log and the individual reflection note."]
},
{
 "no": 51, "module": "5", "title": "DCL Commands - GRANT and REVOKE; TPL - BEGIN TRANSACTION, COMMIT, ROLLBACK, SAVEPOINT",
 "breakdown": [("Data Control Language (DCL) commands", "10 Min", "Discussion"),
   ("Grant and Revoke", "20 Min", "PPT, Smartboard"),
   ("Transaction Processing Language (TPL)", "10 Min", "PPT, Smartboard"),
   ("BEGIN TRANSACTION", "10 Min", "PPT, Smartboard"),
   ("COMMIT, ROLLBACK and SAVEPOINT", "30 Min", "PPT, Smartboard, SQL Plus"),
   ("ROLLBACK TO SAVEPOINT", "10 Min", "PPT, Smartboard"),
   ("Practical 7: Using GRANT and REVOKE", "30 Min", "SQL Plus")],
 "exec": "Executed as a paired practical - students work in pairs as two different database users and grant, use and revoke privileges on each other's objects in real time, immediately seeing the ORA-00942 error when a privilege is missing or revoked. This makes access control tangible. The transaction control portion revisits COMMIT, ROLLBACK and SAVEPOINT now in the context of a banking application and connects back to the ACID discussion of Session 30.",
 "sop": [
   "Step 1 (10 min): Outcome stated - 'student will grant and revoke object and system privileges correctly and will control transaction boundaries in a multi-user environment.'",
   "Step 2 (20 min): GRANT and REVOKE of object privileges (SELECT, INSERT, UPDATE, DELETE), WITH GRANT OPTION and the cascading effect of a revoke demonstrated live between two student schemas.",
   "Step 3 (20 min): TPL concepts revisited - implicit transaction start, COMMIT, ROLLBACK and SAVEPOINT, and the behaviour of a DDL in the middle of a transaction.",
   "Step 4 (20 min): ROLLBACK TO SAVEPOINT demonstrated on a multi-step banking transaction; students predict the final row count before the statement is run and then verify.",
   "Step 5 (30 min): Practical 7 executed in pairs; each pair records the error observed before the grant and after the revoke.",
   "Deliverable: A privilege log sheet per pair showing the statement, the user who ran it, and the result or error before and after each grant and revoke."],
 "questions": [
   "A reporting team needs read-only access to two tables of your schema and must not be able to pass this access to anyone else. Write the exact statements, verify from the other session, and then revoke the access. (Industry task)",
   "User A granted SELECT to user B with the grant option, and B granted it to C. A now revokes from B. State what happens to C's access and justify the Oracle behaviour. (Senior-level, analytical)",
   "A bank transaction must insert three rows, and if the third fails, the first two must still be retained but a fourth corrective row must be added. Write the complete statement sequence using SAVEPOINT. (Open-book, application-oriented)"],
 "homework": ["Create the ACCOUNT table and perform the SAVEPOINT, COMMIT and ROLLBACK exercises listed in the original plan, recording the output after each step."]
},
{
 "no": 52, "module": "5", "title": "Locking Strategies - Implicit and Explicit Locking, LOCK TABLE Command",
 "breakdown": [("Revision", "10 Min", "Discussion"),
   ("Locking strategies - introduction", "10 Min", "PPT, Smartboard"),
   ("Implicit locking", "20 Min", "PPT, Smartboard"),
   ("Explicit locking", "20 Min", "PPT, Smartboard"),
   ("LOCK TABLE command", "15 Min", "SQL Plus"),
   ("Practical 8: Demonstrating transaction control with SAVEPOINT and rollback", "25 Min", "SQL Plus"),
   ("Practical Assignment-8: Problem solving and practice (Q27-Q28)", "20 Min", "SQL Plus")],
 "exec": "Locking is demonstrated, not described. Two students update the same row from two sessions and the class watches the second session hang, which is a row-level lock experienced live. The lock is then released by a commit and the second session proceeds. A deadlock is created deliberately between two sessions to show Oracle's automatic detection and the ORA-00060 message. SELECT FOR UPDATE and LOCK TABLE are then introduced as the explicit controls used in booking systems.",
 "sop": [
   "Step 1 (10 min): Revision of transactions; outcome stated - 'student will explain and demonstrate locking behaviour in a multi-user database and will use explicit locks appropriately.'",
   "Step 2 (20 min): Implicit row-level locking demonstrated by two students updating the same row from two sessions; the class observes the blocked session and the release on commit.",
   "Step 3 (15 min): Deadlock created deliberately between two sessions in reverse order; ORA-00060 shown and the prevention rule (consistent access order) derived.",
   "Step 4 (20 min): SELECT FOR UPDATE, NOWAIT and LOCK TABLE in various modes demonstrated with the seat-booking scenario.",
   "Step 5 (25 min): Practical 8 executed in pairs with an observation log of which session waited and for how long.",
   "Step 6 (20 min): Assignment-8 Q27-Q28 solved.",
   "Deliverable: A locking observation log recording the blocked session, the waiting time, the deadlock error number and the resolution."],
 "questions": [
   "Two counter clerks of a cinema try to book the same seat at the same instant. Explain the exact locking behaviour Oracle applies, write the SELECT FOR UPDATE statement that makes the booking safe, and state what the second clerk sees. (Real-time scenario)",
   "A nightly batch job and an online user deadlocked at 2 am and the job aborted with ORA-00060. Explain how the deadlock arose and state the one design discipline that prevents such deadlocks. (Industry incident)",
   "Explain the practical difference between SELECT FOR UPDATE and SELECT FOR UPDATE NOWAIT, and state which one a customer-facing booking screen should use and why. (Open-book, senior-level judgement)"],
 "homework": ["Complete all pending practical and assignment work before the Module-5 evaluation."]
},
{
 "no": 53, "module": "5", "title": "Oracle Database Privileges and Roles - System and Object Privileges, Assigning, Viewing, Revoking, Roles",
 "breakdown": [("ORACLE database privileges and roles", "10 Min", "Discussion"),
   ("System privileges", "10 Min", "PPT, Smartboard"),
   ("Object privileges", "10 Min", "PPT, Smartboard"),
   ("Assigning privileges", "10 Min", "PPT, Smartboard"),
   ("Viewing privileges", "20 Min", "PPT, Smartboard"),
   ("Revoking privileges", "20 Min", "PPT, Smartboard"),
   ("Roles - create, grant, view and delete", "20 Min", "PPT, Smartboard"),
   ("Practical Assignment-8: Problem solving and practice (Q29)", "20 Min", "SQL Plus")],
 "exec": "The final conceptual session implements the access control matrix that students designed in the Module-4 AI security activity. Roles are introduced as the solution to the unmanageable position of granting privileges to 50 individual users, and students implement the complete role structure of their own domain application, then verify it through the dictionary views USER_SYS_PRIVS, USER_TAB_PRIVS and USER_ROLE_PRIVS - which is exactly how an auditor verifies access in a real organisation.",
 "sop": [
   "Step 1 (10 min): The 50-user problem posed; outcome stated - 'student will implement and audit a complete role-based access control scheme.'",
   "Step 2 (20 min): System versus object privileges distinguished with examples; the ANY privileges and their risk discussed.",
   "Step 3 (20 min): Roles created, privileges granted to roles, roles granted to users, default roles, and role removal demonstrated live.",
   "Step 4 (20 min): Viewing privileges through USER_SYS_PRIVS, USER_TAB_PRIVS, USER_ROLE_PRIVS and SESSION_PRIVS; students audit their own account.",
   "Step 5 (20 min): Revoking privileges and roles, and the effect on currently connected sessions, demonstrated.",
   "Step 6 (20 min): Assignment-8 Q29 solved - the full role implementation of the student's own domain application.",
   "Deliverable: Implemented role structure with a privilege audit report generated from the dictionary views, matching the access control matrix designed earlier."],
 "questions": [
   "Implement the access control matrix your group designed in the AI security activity using roles - create the roles, grant the privileges, assign them to users, and produce the audit report from the dictionary views that proves correct implementation. (Integrated industry task)",
   "A developer has been granted SELECT ANY TABLE 'temporarily' on the production database. State the specific risk, the minimum alternative privilege set, and the statements to correct the position. (Real-life audit finding)",
   "An auditor asks you to prove which users can modify the SALARY table. Write the queries you would run on the dictionary views and explain how a privilege granted through a role would appear in your output. (Open-book, senior-level)"],
 "homework": ["Complete the three privilege and role exercises listed in the original plan - create a user with CREATE SESSION and CREATE TABLE, grant and revoke SELECT and UPDATE on EMPLOYEE, and create, assign and remove the EMP_ROLE role."]
},
{
 "no": "54 (Exam)", "module": "3, 4 & 5", "title": "Sessional Examination - II (Module 3, 4 and 5)",
 "breakdown": [("Sessional Examination - II (Module 3, 4 and 5) as per institute examination schedule", "120 Min", "Examination")],
 "exec": "Formal second sessional examination covering Modules 3, 4 and 5, set to the PLM standard with a majority of application, case-based and open-book style questions drawn from the session-wise question banks of Sessions 23 to 53.",
 "sop": [
   "Step 1: Common question paper prepared jointly by MCS, DPZ and YGL with a minimum of 50 percent application and case-based questions and at least one open-book query-writing question.",
   "Step 2: Examination conducted as per the examination cell seating and timing plan.",
   "Step 3: Evaluation against a common rubric agreed by all three faculty members before assessment begins.",
   "Step 4: Question-wise performance analysis prepared and shared.",
   "Step 5: Remedial sessions scheduled for the identified weak topics before the end-semester examination.",
   "Deliverable: Evaluated answer sheets, question-wise analysis and remedial plan."],
 "questions": [
   "Paper to include a full case-based design and query question on a given business domain.",
   "Paper to include a PL/SQL program-writing question with mandatory exception handling.",
   "Paper to include an unsolved production-situation question on locking, privileges or recovery."],
 "homework": ["Review the evaluated paper and submit corrections of all wrong answers."]
},
{
 "no": 55, "module": "5", "title": "Database Innovation Hackathon using AI (AI Activity)",
 "breakdown": [("Develop a mini database solution collaboratively - briefing", "15 Min", "Instructor Briefing"),
   ("Teams design and implement a complete database application", "60 Min", "Implementation"),
   ("Include procedures, functions, triggers, security and reports", "15 Min", "Discussion"),
   ("Present the final solution", "30 Min", "Presentation")],
 "exec": "Capstone activity of the subject. Teams build a complete working database application for a self-chosen problem within a fixed time, using AI assistance where useful but validating every generated artefact. The solution must include a normalized schema, constraints, a package of procedures and functions, at least two triggers, a role-based security scheme and three management reports - that is, every major outcome of the subject in one deliverable. Judging is done against an industry-style rubric and the best solutions are recommended for the departmental project showcase.",
 "sop": [
   "Step 1 (15 min): Teams of 4 formed, problem statements approved by the faculty, rubric announced (schema and normalization 20, program units 20, triggers and security 20, reports 20, presentation and AI reflection 20).",
   "Step 2 (20 min): Design sprint - ER diagram, normalized schema and the list of three reports to be produced, approved by faculty before coding starts.",
   "Step 3 (40 min): Implementation sprint - tables with constraints, package with procedures and functions, triggers for audit and rule enforcement, roles and grants.",
   "Step 4 (15 min): Report sprint - three management queries executed and their output captured; AI-generated code validated and the correction log completed.",
   "Step 5 (30 min): Each team demonstrates the working solution for 5 minutes, answers cross-questions from the panel and states two limitations of its design.",
   "Step 6: Final submission on ERP - script file, design document, report output and AI reflection note.",
   "Deliverable: A complete working database application with script, design document, report output and AI usage reflection, evaluated against the hackathon rubric."],
 "questions": [
   "For your hackathon problem, state the three reports the management of that organisation would need weekly and write the SQL that produces them. (Industry-oriented)",
   "Identify one business rule in your solution that you enforced with a trigger and explain why a constraint could not have done it. (Design justification)",
   "State one limitation of your solution that would appear only when the data grows to 10 lakh rows, and the change you would make to address it. (Senior-level, scalability)"],
 "homework": ["Upload the final hackathon submission with all artefacts; complete any pending ALA and SEE deliverables."]
},
]
