SESSIONS_1_18 = [
{
 "no": 1, "module": "1", "title": "Introduction to DBMS and its Terminologies",
 "breakdown": [("Subject Introduction and Evaluation Methodology", "20 Min", "Explanation, Smartboard"),
   ("Oracle Installation", "40 Min", "Smartboard, Laptop"),
   ("Introduction of DBMS", "10 Min", "PPT, Smartboard"),
   ("Introduction, Data, Information", "15 Min", "PPT, Smartboard"),
   ("Data Items, Fields, Records, Files", "20 Min", "PPT, Smartboard"),
   ("Data Dictionary, Metadata, Database, Database Systems", "15 Min", "PPT, Smartboard"),
   ("Revision", "10 Min", "Discussion")],
 "exec": "Session starts with an interactive orientation on the subject, PLM evaluation pattern (SEE, CCE, ALA, Sessional) and the industry relevance of DBMS. Faculty demonstrates live Oracle 21c XE + SQL*Plus installation on the smartboard while students mirror the same on their own laptops (learning-by-doing). Concepts of data vs information are built using a live, relatable dataset - the class attendance register and a Swiggy/Zomato order slip - converted step by step into fields, records and files. Metadata and data dictionary are explained by opening an actual table description in SQL*Plus. Methodology: demonstration + guided hands-on + question-answer + concept mapping on board.",
 "sop": [
   "Step 1 (05 min): Faculty takes attendance, states the session outcome on the board: 'By the end of this session every student will have a working Oracle instance and will be able to classify data, information and metadata for a real dataset.'",
   "Step 2 (20 min): Faculty explains syllabus, module split, PLM evaluation methodology (SEE-1 to SEE-5, CCE, ALA, Sessional-I & II) and the practical/assignment submission process on ERP.",
   "Step 3 (40 min): Faculty demonstrates Oracle XE installation step-by-step; students install in parallel; faculty and class CR move around to resolve errors (port conflict, listener, password policy). Checkpoint: every student runs CONNECT system/<pwd> and gets 'Connected'.",
   "Step 4 (25 min): Faculty shows a printed Zomato order receipt and the college attendance sheet, asks students to identify raw data and derived information; builds the Data to Information to Knowledge chain on the smartboard.",
   "Step 5 (20 min): Faculty maps the same receipt into data items, fields, records and a file; then runs DESC and SELECT * FROM USER_TAB_COLUMNS in SQL*Plus to show that the metadata itself is stored as data.",
   "Step 6 (10 min): Rapid-fire oral revision; students write a 3-line reflection 'one thing I installed, one thing I understood, one doubt'.",
   "Deliverable: Working Oracle installation screenshot (uploaded to ERP) + handwritten data dictionary of any one real-life document."],
 "questions": [
   "A local medical store keeps a paper bill containing bill no., date, customer name, medicine name, batch no., expiry date, quantity and amount. Identify which of these are data items, which form a record and what constitutes the file. Justify why expiry date must be stored as DATE and not as text. (Open-book)",
   "Zomato stores crores of orders every month. Explain with a concrete example what 'information' the business extracts from this raw order data that a restaurant owner would actually pay for. Write the two columns you would need for each insight.",
   "Your senior at an IT company says 'we never hard-code column names, we read them from the data dictionary'. Using USER_TAB_COLUMNS, write the query you would run to list every column name and datatype of a table whose structure you have never seen. (Unsolved/practical)"],
 "homework": ["Complete Oracle installation if pending and upload the screenshot.",
   "Prepare the data dictionary of a Student table.",
   "Prepare the data dictionary of an Employee table."]
},
{
 "no": 2, "module": "1", "title": "DBMS Purpose and Applications, Oracle Database and RDBMS Architecture",
 "breakdown": [("Database management system: Introduction, Purpose, Applications", "15 Min", "PPT, Smartboard"),
   ("Introduction to Oracle Database, RDBMS Architecture", "10 Min", "PPT, Smartboard"),
   ("Explanation of SEE-1 and CCE of Module 1 - student instructions", "15 Min", "Explanation"),
   ("Practical 1: SQL queries for creating and describing tables (CREATE, DESC)", "15 Min", "SQL Plus"),
   ("Practical 9: Create student table with common data types using DDL", "15 Min", "SQL Plus"),
   ("Practical Assignment-1: Problem solving and practice (Q1-Q5)", "40 Min", "SQL Plus"),
   ("Revision", "15 Min", "Discussion")],
 "exec": "Session is executed as a problem-first class. Faculty opens with a real failure story - a college that maintained results in Excel and lost consistency during re-evaluation - and asks students to list the problems (redundancy, inconsistency, concurrent access, security, atomicity). Each problem is then mapped live to the DBMS feature that solves it. RDBMS architecture is explained using a drawn client-server diagram and verified practically by showing SQL*Plus (client) talking to the Oracle instance (server). Second half is a fully hands-on lab where every student creates and describes tables and attempts Assignment-1 Q1-Q5 on their own machine while faculty does bench-wise verification.",
 "sop": [
   "Step 1 (05 min): State outcome - 'student will justify why a business must move from file system to DBMS and will independently create and describe tables in Oracle.'",
   "Step 2 (15 min): Case discussion on Excel-based result management failure; students list drawbacks in pairs; faculty consolidates them on board and maps each to a DBMS purpose.",
   "Step 3 (10 min): Faculty explains Oracle client-server RDBMS architecture with a labelled diagram; relates SQL*Plus, listener and instance to what students installed in Session 1.",
   "Step 4 (15 min): Faculty explains SEE-1 and CCE rubric of Module 1, submission format, deadline and ERP upload procedure. Students note it in their lab file.",
   "Step 5 (30 min): Guided practical - faculty demonstrates CREATE TABLE and DESC once, then students execute Practical 1 and Practical 9 independently; faculty verifies output on at least 50 percent of machines.",
   "Step 6 (40 min): Students solve Assignment-1 Q1-Q5 individually; faculty circulates, notes common errors (missing datatype size, reserved words) and corrects them publicly on the smartboard.",
   "Step 7 (15 min): Revision through 5 oral questions; doubts logged for next session.",
   "Deliverable: Executed Practical 1 and 9 with output pasted in the lab file; Assignment-1 Q1-Q5 solved."],
 "questions": [
   "A hospital currently maintains patient records in separate Excel files kept by the OPD, the lab and the pharmacy. Identify any four problems that will certainly occur, and state which specific DBMS feature removes each one. (Case-based)",
   "Design and create the table structure that an e-commerce startup would need to store product details, choosing the correct Oracle datatype and size for each column. Justify why you chose NUMBER(8,2) over NUMBER for price. (Open-book)",
   "Your team lead asks you to verify, without opening any design document, whether a production table ORDERS has a column for GST amount and what its datatype is. Write the exact commands you would run and explain the output you expect."],
 "homework": ["Create table EMPLOYEE with employee_id (number), employee_name (varchar2), dob (date), email (varchar2).",
   "Create table DEPARTMENT with department_id, department_name, location, budget.",
   "Alter EMPLOYEE to add phone_number (varchar2).",
   "Rename column email in EMPLOYEE to employee_email.",
   "Drop the DEPARTMENT table."]
},
{
 "no": 3, "module": "1", "title": "Open Source vs Commercial DBMS, Data Types in Oracle, DDL Commands",
 "breakdown": [("Open source and Commercial DBMS (MySQL, Oracle, DB2, SQL Server)", "10 Min", "PPT, Smartboard"),
   ("Basics of SQL: Data Types in Oracle", "10 Min", "PPT, Smartboard"),
   ("About SQL Commands and its types", "15 Min", "PPT, Smartboard"),
   ("DDL Commands: CREATE, ALTER, DROP", "20 Min", "PPT, Smartboard, SQL Plus"),
   ("Practical 2: Modifying tables using ALTER", "10 Min", "SQL Plus"),
   ("Practical 3: Deleting tables using DROP", "05 Min", "SQL Plus"),
   ("Practical Assignment-1: Problem solving and practice (Q6-Q14)", "35 Min", "SQL Plus"),
   ("Revision", "10 Min", "Discussion")],
 "exec": "Conducted as comparison-and-demonstration session. Faculty puts a procurement scenario on the board - 'a 20-member startup must choose a database within a 2 lakh budget' - and students compare MySQL, PostgreSQL, Oracle and SQL Server on cost, support, scalability and licensing. Oracle datatypes are taught through a 'choose the right datatype' rapid activity using real columns (Aadhaar no., PIN code, salary, remarks, joining date). DDL is demonstrated live with immediate student replication, including the deliberate demonstration of a DROP mistake and the FLASHBACK/recycle bin recovery, so students understand DDL is auto-committed.",
 "sop": [
   "Step 1 (05 min): Outcome stated - 'student will select an appropriate DBMS product and correct datatypes for a given business case and will apply CREATE, ALTER, DROP confidently.'",
   "Step 2 (10 min): Startup procurement case; students work in pairs for 4 minutes and present a one-line recommendation with justification; faculty tabulates the comparison on the smartboard.",
   "Step 3 (10 min): Datatype drill - faculty names a real column, students call out the datatype and size; faculty corrects misconceptions (CHAR vs VARCHAR2, NUMBER precision, DATE vs TIMESTAMP).",
   "Step 4 (15 min): Classification of SQL commands DDL, DML, DQL, DCL, TCL with one live example of each.",
   "Step 5 (20 min): Live demonstration of CREATE, ALTER (ADD, MODIFY, RENAME) and DROP; faculty drops a table deliberately and recovers it from the recycle bin to prove DDL behaviour.",
   "Step 6 (15 min): Students execute Practical 2 and Practical 3 on their machines; faculty verifies output.",
   "Step 7 (35 min): Assignment-1 Q6-Q14 solved individually; faculty resolves doubts bench-wise and notes repeated errors.",
   "Step 8 (10 min): Oral revision and summary of DDL syntax card pasted in the lab file.",
   "Deliverable: Practical 2 and 3 completed; Assignment-1 Q6-Q14 solved; one-page DBMS comparison chart."],
 "questions": [
   "A fintech startup expects 50,000 transactions a day and must satisfy RBI audit requirements. Recommend an open-source or commercial DBMS, giving three technical and two commercial reasons. State one risk of your own recommendation. (Industry case)",
   "For a government portal you must store: Aadhaar number, PIN code, monthly income, date of application and a 500-word grievance text. Give the exact Oracle datatype with size for each and explain why NUMBER is wrong for Aadhaar and PIN code. (Open-book)",
   "A junior developer ran DROP TABLE CUSTOMER on the production schema at 4 pm. Explain what exactly happened to the data and the transaction, and write the statement sequence you would use to recover the table. Also state one preventive control."],
 "homework": ["Create table DEPARTMENT with department_id, department_name, location, head_of_department.",
   "Create table EXAM with exam_id, exam_name, exam_date, total_marks, course_id.",
   "Alter DEPARTMENT to add contact_number (varchar2).",
   "Rename exam_name in EXAM to exam_title.",
   "Drop the EXAM table."]
},
{
 "no": 4, "module": "1", "title": "DML Commands - INSERT, UPDATE, DELETE",
 "breakdown": [("Revision", "10 Min", "Discussion"),
   ("DML Commands: INSERT", "15 Min", "PPT, Smartboard, SQL Plus"),
   ("DML Commands: UPDATE", "10 Min", "PPT, Smartboard, SQL Plus"),
   ("DML Commands: DELETE", "10 Min", "PPT, Smartboard, SQL Plus"),
   ("Practical 4: Create table and insert sample data", "15 Min", "SQL Plus"),
   ("Practical 8: Create Students and Employees tables with 5 fields and insert data", "15 Min", "SQL Plus"),
   ("Practical 5: Inserting and updating records using INSERT, UPDATE, DELETE", "10 Min", "SQL Plus"),
   ("Practical Assignment-1: Problem solving and practice (Q15-Q20)", "35 Min", "SQL Plus")],
 "exec": "Executed as a simulated data-entry operator role-play. Each student acts as a back-office executive of a courier company and must load, correct and remove shipment records using DML. Faculty demonstrates the single most important industry lesson of this session - an UPDATE or DELETE without a WHERE clause - by running it on a dummy table and showing all rows affected, then rolling it back. Students then practise insert variants (all columns, selected columns, NULL handling, INSERT with SELECT). The session is largely lab-driven with 75 minutes of continuous hands-on work.",
 "sop": [
   "Step 1 (10 min): Revision of DDL through 5 oral questions; faculty states the outcome - 'student will manipulate live data safely using INSERT, UPDATE and DELETE with correct filtering.'",
   "Step 2 (15 min): Faculty demonstrates INSERT in three forms - all columns, selected columns, and INSERT ... SELECT - on a COURIER table created live.",
   "Step 3 (10 min): UPDATE demonstrated with and without WHERE; faculty shows 'rows updated' count, then ROLLBACK, and derives the rule: always SELECT before you UPDATE.",
   "Step 4 (10 min): DELETE demonstrated and compared with TRUNCATE and DROP in a three-column board table.",
   "Step 5 (40 min): Students execute Practical 4, Practical 8 and Practical 5 independently; faculty checks the row counts on each machine before signing the lab file.",
   "Step 6 (35 min): Assignment-1 Q15-Q20 solved individually; faculty gives a 2-minute correction talk on the two most common errors observed.",
   "Deliverable: Students and Employees tables populated with at least 5 valid records each, with evidence of one update and one delete operation."],
 "questions": [
   "A courier company's operator updated the delivery status of all 12,000 shipments instead of one because the WHERE clause was missed. Explain what you would do in the next 60 seconds if the transaction is not yet committed, and what you would do if it is already committed. Write the exact statements. (Real-time situation)",
   "Write a single statement that increases the salary of all employees of the 'Sales' department by 8 percent but only for those who joined before 01-JAN-2023, and then write the SELECT you would run first to verify how many rows will be affected. (Open-book)",
   "A bank must archive all accounts with zero balance that have been inactive for two years into a table OLD_ACCOUNT and then remove them from ACCOUNT. Write the complete sequence of DML statements in the correct order and explain why that order matters."],
 "homework": ["Insert 5 records into the LIBRARY table.", "Insert 3 records into the DEPARTMENT table.",
   "Update the salary of the teacher where teacher_id = 101.", "Delete the record from COURSE where course_id = 3.",
   "Update available_copies in LIBRARY where book_id = 1."]
},
{
 "no": 5, "module": "1", "title": "DQL Commands - SELECT with WHERE and ORDER BY, Aggregate Functions",
 "breakdown": [("Revision", "10 Min", "Discussion"),
   ("DQL Command: SELECT with WHERE Clause", "15 Min", "PPT, Smartboard, SQL Plus"),
   ("DQL Command: SELECT with ORDER BY", "20 Min", "PPT, Smartboard, SQL Plus"),
   ("Aggregate Functions - examples", "20 Min", "PPT, Smartboard, SQL Plus"),
   ("Practical 6: Retrieving data using SELECT, WHERE, ORDER BY", "10 Min", "SQL Plus"),
   ("Practical Assignment-1: Problem solving and practice (Q21-Q22)", "45 Min", "SQL Plus")],
 "exec": "Conducted as a 'business question to SQL query' translation workshop. Faculty writes business questions asked by a real sales manager (top 5 highest paid employees, employees who joined this quarter, average salary per city) and students translate each into SQL within a fixed time. A pre-loaded EMPLOYEE table of 25 rows is distributed as a script so that every student works on identical data and outputs can be compared instantly. Peer-checking is used: students exchange machines and verify each other's output against the expected result shown on the smartboard.",
 "sop": [
   "Step 1 (10 min): Revision of DML; faculty runs the data-load script on all machines and states the outcome - 'student will convert a business requirement into a correct SELECT query with filtering and sorting.'",
   "Step 2 (15 min): WHERE clause with relational, logical and NULL operators demonstrated; faculty highlights the IS NULL trap (= NULL returns no rows).",
   "Step 3 (20 min): ORDER BY on single and multiple columns, ASC/DESC, ordering by column position and by expression; TOP-N logic shown using ROWNUM with a sorted inline view.",
   "Step 4 (20 min): Aggregate functions COUNT, SUM, AVG, MIN, MAX demonstrated; faculty deliberately shows COUNT(*) vs COUNT(column) difference on a column containing NULLs.",
   "Step 5 (10 min): Students execute Practical 6 and get the output verified.",
   "Step 6 (45 min): Assignment-1 Q21-Q22 plus the business-question drill; students exchange seats for peer verification in the last 10 minutes.",
   "Deliverable: Query sheet with 8 business questions and the student's SQL solution with output, peer-verified and signed."],
 "questions": [
   "The sales head of a retail chain asks: 'show me the five highest paid employees of the Surat branch, highest first'. Write the query and then explain what will change in your query if two employees have exactly the same salary at the fifth position. (Industry scenario)",
   "An HR dashboard shows 'Average Salary = 42,000' but the finance team computes 38,500 from the same table. The salary column contains NULL for 12 employees. Explain the difference mathematically and write the query that reproduces each of the two values. (Case-based analysis)",
   "Using the EMPLOYEE table, write queries to answer: total payroll cost per department, the department with the maximum headcount, and the number of employees who have no manager assigned. State which of these cannot be answered by COUNT(*) and why. (Open-book)"],
 "homework": ["Create table EMPLOYEE(emp_id, emp_name, department, salary, joining_date), add 25 records and apply Q1-Q10 insert/update/delete queries given in the original plan."]
},
{
 "no": 6, "module": "1", "title": "DQL - ORDER BY and HAVING Clauses, Data Dictionary in Oracle",
 "breakdown": [("Revision", "15 Min", "Discussion"),
   ("DQL Command: SELECT with GROUP BY, ORDER BY and HAVING Clauses", "20 Min", "PPT, Smartboard, SQL Plus"),
   ("Practical 7: Aggregate functions with GROUP BY and HAVING", "10 Min", "SQL Plus"),
   ("Practical Assignment-2: Problem solving and practice (Q1-Q2)", "40 Min", "SQL Plus"),
   ("Use of Data Dictionary in Oracle (USER_TABLES, ALL_TABLES)", "15 Min", "SQL Plus"),
   ("Complete pending assignment and homework", "20 Min", "SQL Plus")],
 "exec": "Executed as an analytics-report building session. Students are given a role - MIS executive who must produce a department-wise salary report with exceptions. The WHERE vs HAVING distinction, which is the most frequently examined concept, is taught by making students deliberately write a wrong query using WHERE with an aggregate, observing the Oracle error, and then correcting it. The data dictionary portion is executed as a discovery exercise where students explore their own schema using USER_TABLES, USER_TAB_COLUMNS and USER_CONSTRAINTS and document what they find.",
 "sop": [
   "Step 1 (15 min): Revision of aggregates; outcome stated - 'student will produce grouped analytical reports and will explore schema metadata independently.'",
   "Step 2 (20 min): GROUP BY logic explained with a physical grouping activity (students physically group by branch), then HAVING is introduced as 'filter after grouping'; faculty shows the ORA-00934 error from using WHERE with an aggregate and corrects it.",
   "Step 3 (10 min): Students execute Practical 7 and verify the grouped output.",
   "Step 4 (40 min): Assignment-2 Q1-Q2 solved individually with faculty circulation.",
   "Step 5 (15 min): Data dictionary discovery - each student runs queries on USER_TABLES and USER_TAB_COLUMNS and writes down how many tables they own and which table has the most columns.",
   "Step 6 (20 min): Buffer slot for completing pending practicals and homework; faculty signs completed lab files.",
   "Deliverable: Department-wise analytical report query sheet and a schema inventory note generated from the data dictionary."],
 "questions": [
   "An MIS executive must list only those departments whose average salary exceeds 50,000 and which have more than 3 employees, sorted by average salary descending. Write the query and explain exactly why the two conditions cannot be placed in the WHERE clause. (Open-book)",
   "A manager claims 'our Pune branch has the highest total sales'. Using a SALES(branch, sales_person, amount, sale_date) table, write the queries that would either prove or disprove this claim for the current financial year, and state one way the claim could be misleading. (Analytical)",
   "You join a project and get access to a schema with no documentation. Write the data dictionary queries you would run to find (i) all table names you own, (ii) all columns of the largest table, (iii) all constraints defined on it. (Practical, industry-oriented)"],
 "homework": ["Create a Student table with Student_ID, Student_Name, Department, Semester, Marks and insert 10 records; then run the five retrieval/update/delete queries listed in the original plan."]
},
{
 "no": 7, "module": "1", "title": "Database Design Activity - Design Your College Database (Group Activity)",
 "breakdown": [("Group formation and problem briefing", "10 Min", "Explanation"),
   ("Design a database for a college management system - identify entities, fields, records, tables", "115 Min", "Database Design Activity"),
   ("Activity work submission", "05 Min", "Submission")],
 "exec": "Full activity-based learning session. Students work in groups of 3-4 as a 'database consulting team' for the college. Each group is assigned one real sub-system (Admission, Library, Examination, Hostel, Placement) so that no two groups produce the same output and the outputs can later be integrated into one college database. Groups identify entities, attributes, keys and relationships, prepare a complete data dictionary and present the structure using a chart or a Lucidchart diagram. Faculty acts as the 'client' and challenges each group with a change request during the design to test flexibility of their model.",
 "sop": [
   "Step 1 (10 min): Faculty forms groups of 3-4, allots one college sub-system per group and shares the evaluation rubric (entity identification 30 percent, data dictionary 30 percent, diagram 20 percent, presentation 20 percent).",
   "Step 2 (25 min): Groups list all entities and attributes of their sub-system on a worksheet; faculty verifies that each group has at least 4 entities.",
   "Step 3 (35 min): Groups define datatypes, primary keys and foreign keys for each table and prepare a complete data dictionary in the prescribed format.",
   "Step 4 (20 min): Faculty visits each group as the 'client' and gives one change request (for example 'a student can now take two hostel rooms in a year'); groups modify the design and record the impact.",
   "Step 5 (30 min): Groups prepare the chart or diagram and a 3-minute presentation; two groups present and the class cross-questions.",
   "Step 6 (05 min): Submission of the data dictionary sheet and diagram on ERP with all group member names and the contribution of each.",
   "Deliverable: Complete data dictionary and structure diagram of one college sub-system per group, with a change-impact note."],
 "questions": [
   "Your group designed the Library sub-system. The college now says a single book can be issued to a student as well as reserved by another at the same time. Redesign the affected table(s) and justify the change in one paragraph. (Change-request case)",
   "Identify three attributes in your college design that look like a single field but must actually be split into separate columns (for example address). Explain the practical problem that would arise at report time if they are not split. (Application-oriented)",
   "Two groups designed STUDENT and FEES separately. Explain what common key must exist for the two to be integrated, and write the CREATE TABLE statement for FEES with the correct foreign key. (Open-book integration task)"],
 "homework": ["Complete and upload the group data dictionary and design diagram on ERP."]
},
{
 "no": 8, "module": "1", "title": "DDL Commands, DML Commands and Data Dictionary - Practical Session",
 "breakdown": [("Revision", "15 Min", "Discussion"),
   ("Practical 10: Create 5 tables and perform all DDL operations on them", "20 Min", "SQL Plus"),
   ("Practical 11: Insert sample data and verify insertion", "20 Min", "SQL Plus"),
   ("Practical 16: Browsing data dictionary - USER_TABLES, ALL_TABLES", "15 Min", "SQL Plus"),
   ("Practical Assignment-2: Problem solving and practice (Q3-Q4)", "40 Min", "SQL Plus"),
   ("Revision", "15 Min", "Discussion")],
 "exec": "Pure laboratory execution session conducted in 'build your own schema' mode. Each student implements the college sub-system designed in Session 7 as actual tables, thereby connecting design to implementation. Faculty follows a checkpoint model - students must get each practical verified before moving to the next. The data dictionary practical is executed as a self-audit where students verify their own created objects through USER_TABLES rather than by memory.",
 "sop": [
   "Step 1 (15 min): Revision of DDL and DML syntax; outcome stated - 'student will implement a designed schema end-to-end and will verify it through the data dictionary.'",
   "Step 2 (20 min): Practical 10 - students create 5 tables from their Session 7 design and perform ADD, MODIFY, RENAME and DROP COLUMN operations. Checkpoint 1 verified by faculty.",
   "Step 3 (20 min): Practical 11 - insert at least 5 valid rows into each table and verify through SELECT and COUNT(*). Checkpoint 2.",
   "Step 4 (15 min): Practical 16 - students query USER_TABLES and ALL_TABLES, compare the two and record the difference in their lab file.",
   "Step 5 (40 min): Assignment-2 Q3-Q4 solved; faculty resolves individual doubts and marks the lab file.",
   "Step 6 (15 min): Class-level revision of the errors most frequently seen during the session.",
   "Deliverable: Five implemented and populated tables verified through the data dictionary, lab file signed."],
 "questions": [
   "You created a table with 5 columns but later realise column marks must not accept negative values and column email must be unique. Write the ALTER statements and explain what will happen if the existing data already violates these rules. (Practical situation)",
   "Explain the practical difference between USER_TABLES, ALL_TABLES and DBA_TABLES with one real situation in which a developer in a company would use each. (Open-book)",
   "A tester reports that your INSERT 'worked' but the row is not visible to his session. Give two possible technical reasons and the exact statement that resolves the issue. (Industry-oriented)"],
 "homework": ["Create a Student table with PRIMARY KEY, NOT NULL and UNIQUE constraints.",
   "Insert at least 5 records, display all records, retrieve department-wise students and count the total students."]
},
{
 "no": 9, "module": "1", "title": "DML, DDL and DQL Commands - Integrated Practical Session",
 "breakdown": [("Revision", "15 Min", "Discussion"),
   ("Practical 12: DML commands - insert 10 records and perform modifications", "15 Min", "SQL Plus"),
   ("Practical 13: Practice DDL-create and DML-insert commands", "15 Min", "SQL Plus"),
   ("Practical 14: Retrieve data using SELECT from tables", "15 Min", "SQL Plus"),
   ("Practical 15: Practice SQL UPDATE and DELETE to modify data", "15 Min", "SQL Plus"),
   ("Practical Assignment-2: Problem solving and practice (Q5-Q6)", "30 Min", "SQL Plus"),
   ("Practical questions checking and submission", "15 Min", "SQL Plus")],
 "exec": "Consolidation lab executed as a timed 'mini sprint'. Students receive a single integrated problem statement (a canteen billing system) and must complete the full cycle - create, insert, retrieve, modify - within fixed time boxes announced by the faculty. This simulates the pace expected in the PLM sessional practical examination. Last 15 minutes are used for formal checking and submission so that no practical remains pending.",
 "sop": [
   "Step 1 (15 min): Revision and announcement of the sprint rules and time boxes; outcome stated - 'student will complete a full DDL-DML-DQL cycle for a given business problem within the examination time limit.'",
   "Step 2 (15 min): Practical 12 executed in a strict 15-minute box; faculty announces the remaining time at 5-minute intervals.",
   "Step 3 (15 min): Practical 13 executed; faculty checks that constraints and datatypes are appropriate, not just syntactically valid.",
   "Step 4 (15 min): Practical 14 - retrieval queries of increasing difficulty; faculty displays the expected output on the smartboard for self-check.",
   "Step 5 (15 min): Practical 15 - UPDATE and DELETE with correct WHERE; faculty insists on a verification SELECT before and after each operation.",
   "Step 6 (30 min): Assignment-2 Q5-Q6 solved.",
   "Step 7 (15 min): Formal checking, viva of two questions per student and submission on ERP.",
   "Deliverable: All pending practicals of Module 1 completed, checked and submitted; sprint performance recorded in CCE."],
 "questions": [
   "For a college canteen, create the required table(s), insert one day of sales, and then answer: which item earned the highest revenue today and which item was not sold at all. Write all statements in sequence. (Integrated practical)",
   "During the sprint, a student's DELETE removed 10 rows instead of 1. Before committing, demonstrate recovery and then write the corrected statement. Explain the one habit that prevents this error. (Real situation)",
   "You have 20 minutes in a practical exam and a question asks for 'the second highest salary'. Write at least two different working approaches and state which one you would submit and why. (Open-book, application-oriented)"],
 "homework": ["Create Student table with Student_ID, Student_Name, Department, Semester, Marks; insert 10 records and complete the five retrieval, update and delete queries given in the original plan."]
},
{
 "no": 10, "module": "1", "title": "Debate Activity - Open Source vs Commercial DBMS and DBMS Vocabulary Crossword",
 "breakdown": [("Discussion groups conducted by selected student chairpersons on Open source DBMS v/s Commercial DBMS", "60 Min", "Discussion"),
   ("Students solve a printed DBMS Vocabulary Crossword in class and submit the scanned copy through the ERP portal", "60 Min", "DBMS Vocabulary Crossword Sheet")],
 "exec": "Activity and communication oriented session. The class is divided into two houses - 'Open Source' and 'Commercial' - with student chairpersons managing the floor while the faculty acts as moderator and timekeeper only. Each house must support arguments with real evidence (licensing cost, TCO, support SLA, known migrations such as companies moving from Oracle to PostgreSQL). The second half is an individual timed crossword on DBMS terminology which reinforces vocabulary needed for theory answers and viva.",
 "sop": [
   "Step 1 (10 min): Faculty divides the class into two houses, appoints two student chairpersons and one timekeeper, and announces the debate rules and the evaluation rubric (content 40, evidence 30, delivery 20, rebuttal 10).",
   "Step 2 (15 min): Preparation time - each house prepares five arguments with supporting facts; use of mobile for fact-checking is permitted and sources must be quoted.",
   "Step 3 (25 min): Debate - 2 minutes per speaker, alternating houses, chairperson manages the sequence.",
   "Step 4 (10 min): Rebuttal round and faculty summary which converts the debate into a decision framework (when to choose open source, when commercial).",
   "Step 5 (50 min): Printed DBMS vocabulary crossword solved individually under examination conditions.",
   "Step 6 (10 min): Scanning and uploading the solved crossword on ERP; faculty records participation marks.",
   "Deliverable: Debate evaluation sheet with individual marks and scanned solved crossword uploaded by each student."],
 "questions": [
   "A 300-bed hospital must choose between PostgreSQL and Oracle for its HIS. Prepare a five-point written recommendation covering licence cost, 24x7 support, compliance and in-house skill availability, and state the decision you would defend before the management. (Case study)",
   "Name one real organisation that migrated from a commercial DBMS to an open-source DBMS and state two technical challenges that such a migration creates at the SQL level (for example datatype and PL/SQL incompatibility). (Research-oriented)",
   "Define in one precise line each, as a sessional answer would require: instance, schema, metadata, data dictionary, DDL, constraint, normalization, cursor. (Open-book vocabulary)"],
 "homework": ["Upload the scanned crossword and submit a one-page written summary of the debate conclusion."]
},
{
 "no": 11, "module": "2", "title": "Architecture of Oracle, Components of DBMS, Data Integrity and Constraints",
 "breakdown": [("Architecture of Oracle: Instance and Database", "30 Min", "PPT, Smartboard"),
   ("Components of DBMS (SGA, PGA, Background Processes, Data Files, Control Files)", "30 Min", "PPT, Smartboard"),
   ("Data Integrity and Constraints: concept and need of constraints", "30 Min", "PPT, Smartboard"),
   ("Practical 1: Apply primary key and NOT NULL constraints", "15 Min", "SQL Plus"),
   ("Practical 2: Implementing NOT NULL, CHECK, UNIQUE", "15 Min", "SQL Plus")],
 "exec": "Architecture is taught using a physical analogy walk-through - the Oracle instance is compared to a bank branch (memory, staff, processes) and the database to its vault (data files, control files, redo logs). Faculty draws the architecture incrementally on the smartboard, adding one component at a time and explaining the failure that occurs if that component is lost. Constraints are introduced through a 'bad data' demonstration - a table without constraints is loaded with duplicate and invalid rows, students see the damage, and then the same table is rebuilt with constraints and the same bad data is rejected by Oracle.",
 "sop": [
   "Step 1 (05 min): Outcome stated - 'student will explain the role of each Oracle architectural component and will enforce data quality at the database level using constraints.'",
   "Step 2 (30 min): Instance vs database explained with the bank-branch analogy; students draw the labelled diagram in their notebooks as the faculty builds it on the board.",
   "Step 3 (30 min): SGA, PGA, background processes (SMON, PMON, DBWR, LGWR, CKPT), data files, control files and redo log files explained; for each component faculty asks 'what breaks if this is lost'.",
   "Step 4 (20 min): Bad-data demonstration - faculty inserts duplicate roll numbers, NULL names and negative marks into an unconstrained table; class lists the business consequences.",
   "Step 5 (10 min): Need and types of constraints derived from the above list; faculty shows the correct CREATE TABLE with constraints and re-runs the same bad inserts to show rejection.",
   "Step 6 (30 min): Students execute Practical 1 and Practical 2 and record the exact Oracle error number for each violation in the lab file.",
   "Deliverable: Labelled Oracle architecture diagram and a constraint-violation error log (error code against violation type)."],
 "questions": [
   "The DBA of a bank reports that the control file is corrupted while the data files are intact. Explain whether the database can be opened, what information was lost, and what recovery step is required. (Industry scenario)",
   "A student result table allowed marks of 150 out of 100 and two students with the same enrolment number. Write the ALTER statements to prevent both problems permanently and state the Oracle error number the user will now see for each violation. (Practical)",
   "Explain with one example each the difference between an Oracle instance and an Oracle database, and state what exactly happens to SGA contents during a SHUTDOWN ABORT. (Open-book, senior-level)"],
 "homework": ["Create STUDENT, EMPLOYEE, PRODUCT, CUSTOMER and COURSE tables with PRIMARY KEY, NOT NULL, CHECK and UNIQUE constraints as given in the original plan and test valid and invalid inserts."]
},
{
 "no": 12, "module": "2", "title": "Database Administrator, DBA Roles and Responsibilities, Constraints - Domain, Entity and Referential",
 "breakdown": [("Database administrator (DBA)", "15 Min", "PPT, Smartboard"),
   ("DBA role and responsibilities", "15 Min", "PPT, Smartboard"),
   ("Domain constraints: NOT NULL, CHECK", "15 Min", "PPT, Smartboard"),
   ("Entity constraints: UNIQUE, PRIMARY KEY", "15 Min", "PPT, Smartboard, SQL Plus"),
   ("Referential constraints: FOREIGN KEY", "15 Min", "PPT, Smartboard, SQL Plus"),
   ("Practical 3: Using IN operator in queries", "15 Min", "SQL Plus"),
   ("Practical 4: Queries involving predicates LIKE, BETWEEN, IN", "15 Min", "SQL Plus"),
   ("Practical 6: Add Primary key, NOT NULL and UNIQUE constraints to your tables", "15 Min", "SQL Plus")],
 "exec": "The DBA portion is delivered as a career-oriented discussion with an actual DBA job description taken from a job portal projected on the smartboard; students map each listed responsibility to the topics of this syllabus. Constraints are classified practically (domain, entity, referential) and demonstrated by building a two-table parent-child model (DEPARTMENT and EMPLOYEE) live, including the deliberate attempt to delete a parent row to show the referential error and the behaviour of ON DELETE CASCADE.",
 "sop": [
   "Step 1 (05 min): Outcome stated - 'student will describe the DBA role in an IT organisation and will implement all three categories of constraints including referential integrity.'",
   "Step 2 (25 min): Real DBA job description discussed; students map responsibilities (backup, tuning, user management, security) to syllabus modules in a two-column table.",
   "Step 3 (15 min): Domain constraints NOT NULL and CHECK implemented live with business rules (salary > 0, gender IN ('M','F','O')).",
   "Step 4 (15 min): Entity constraints UNIQUE and PRIMARY KEY implemented; the difference is proved by inserting a NULL into each.",
   "Step 5 (15 min): Referential constraint - parent-child tables created, child row with invalid parent rejected, parent deletion blocked, then ON DELETE CASCADE demonstrated.",
   "Step 6 (45 min): Students execute Practical 3, 4 and 6; faculty verifies that each student's table shows all constraints in USER_CONSTRAINTS.",
   "Deliverable: Parent-child schema with working referential integrity and a constraint listing taken from USER_CONSTRAINTS."],
 "questions": [
   "An e-commerce company allows a customer to be deleted only if he has no orders. Write the FOREIGN KEY definition that enforces this, then write the alternative definition that would instead delete all his orders automatically, and state which one you would choose for a real business and why. (Industry decision)",
   "A HR table permits two employees with the same official email id and permits a blank department. Write the ALTER statements that fix both, and explain why UNIQUE allows NULL but PRIMARY KEY does not. (Open-book)",
   "From a given DBA job advertisement, list any five responsibilities and state for each the exact SQL feature or Oracle component you have studied that supports it. (Application-oriented)"],
 "homework": ["On the STUDENT table, retrieve records using IN, LIKE and BETWEEN predicates and add PRIMARY KEY, NOT NULL and UNIQUE constraints as specified in the original plan, then verify them."]
},
{
 "no": 13, "module": "2", "title": "Database System Architecture, Data Abstraction, Data Independence, Operators IN, LIKE, BETWEEN",
 "breakdown": [("Revision", "05 Min", "Discussion"),
   ("Database system architecture", "20 Min", "PPT, Smartboard"),
   ("Data abstraction", "15 Min", "PPT, Smartboard"),
   ("Data independence (logical and physical)", "15 Min", "PPT, Smartboard"),
   ("IN operator", "10 Min", "PPT, Smartboard, SQL Plus"),
   ("LIKE operator", "10 Min", "PPT, Smartboard, SQL Plus"),
   ("BETWEEN operator", "10 Min", "PPT, Smartboard, SQL Plus"),
   ("Practical 7: Use foreign keys to establish relationships between tables", "15 Min", "SQL Plus"),
   ("Practical 8: Implement Practical 1 again with referential constraint", "20 Min", "SQL Plus")],
 "exec": "Three-schema architecture is taught top-down using the college ERP that students use daily - the student login screen is the external view, the table design is the conceptual level and the data file on the server is the internal level. Data independence is demonstrated practically by adding a new column to a base table and showing that an existing application query continues to work, which makes an abstract concept concrete. Operators are then practised on a realistic customer dataset where pattern search (LIKE) is used as it is used in a real search box.",
 "sop": [
   "Step 1 (05 min): Revision; outcome stated - 'student will map a real application to the three-schema architecture and will write production-style search queries using IN, LIKE and BETWEEN.'",
   "Step 2 (20 min): Three-level architecture explained using the college ERP screens; students identify which screen belongs to which level.",
   "Step 3 (15 min): Data abstraction levels explained with the same example; students write one real example of each level.",
   "Step 4 (15 min): Logical and physical data independence demonstrated live - a column is added to a base table and an existing view or query is re-run unchanged.",
   "Step 5 (30 min): IN, LIKE (with percent and underscore wildcards) and BETWEEN demonstrated on a 25-row customer table; faculty highlights the inclusive nature of BETWEEN and the date boundary trap.",
   "Step 6 (35 min): Students execute Practical 7 and Practical 8 implementing foreign keys; faculty verifies the referential behaviour on each machine.",
   "Deliverable: Three-schema mapping worksheet of the college ERP and a working two-table referential schema."],
 "questions": [
   "A search box on a travel portal must return all customers whose name starts with 'A', whose city is Ahmedabad, Surat or Rajkot, and whose booking amount is between 5,000 and 20,000. Write the single query, then state one reason why this query may become slow on 10 lakh rows. (Industry problem)",
   "The development team added two new columns to the ORDERS table last night, yet none of the 40 existing reports failed. Name and explain the property of DBMS that made this possible, and describe one change that would have broken the reports. (Analytical)",
   "Write a query using BETWEEN to fetch all transactions of March 2026 from a table where the column is of DATE type with a time component. Explain why the straightforward BETWEEN '01-MAR-2026' AND '31-MAR-2026' may silently miss rows. (Open-book, senior-level trap)"],
 "homework": ["Create EMPLOYEE table with 10 records and write queries using IN, LIKE, BETWEEN and a combination of IN and BETWEEN as listed in the original plan."]
},
{
 "no": 14, "module": "2", "title": "Flipped Classroom Activity (TPA Full Session)",
 "breakdown": [("Flipped classroom - student-led teaching of assigned topics, TPA full session", "120 Min", "Student presentation, Smartboard, SQL Plus")],
 "exec": "Complete flipped classroom. Topics already covered in Module 1 and Module 2 (constraints, Oracle architecture, data independence, operators, aggregate functions) are distributed to student teams one week in advance. In this session students teach, demonstrate on SQL*Plus and set questions for their peers while the faculty only moderates, corrects conceptual errors and evaluates. A Topic Presentation Assessment (TPA) rubric is used for scoring and the session doubles as speaking-skill practice.",
 "sop": [
   "Step 1 (10 min): Faculty announces the order of presentations, the TPA rubric (concept clarity 40, live demonstration 30, question handling 20, presentation 10) and appoints two student evaluators per team.",
   "Step 2 (80 min): Each team gets 8-10 minutes - 4 minutes concept, 3 minutes live SQL demonstration, 3 minutes handling questions from peers and faculty.",
   "Step 3 (15 min): Faculty gives a consolidated correction talk on every conceptual mistake observed, with the correct explanation.",
   "Step 4 (10 min): Peer evaluation sheets collected and marks consolidated with faculty marks.",
   "Step 5 (05 min): Faculty announces the best team and the common weak areas to be revised before Sessional-I.",
   "Deliverable: TPA score sheet per student, presentation files uploaded on ERP and a class-level weak-topic list."],
 "questions": [
   "As the presenting team, demonstrate live why a CHECK constraint is better than validating the same rule in application code. Then answer: name one business rule that cannot be enforced by a CHECK constraint. (Demonstration-based)",
   "A peer asks: 'if the application already validates input, why does the database need constraints at all'. Give a complete answer with one real incident-style example. (Viva-style, application-oriented)",
   "Prepare and submit three examination-standard questions on your assigned topic along with the model answers, at the level expected in the PLM sessional examination. (Open-book question-setting task)"],
 "homework": ["Upload the presentation and the three self-prepared examination questions with model answers."]
},
{
 "no": 15, "module": "2", "title": "Types of DBMS, Aggregate Functions, Inbuilt Numeric Functions",
 "breakdown": [("Revision", "15 Min", "Discussion"),
   ("Types of DBMS - Centralized and Distributed", "30 Min", "PPT, Smartboard"),
   ("Aggregate functions", "20 Min", "PPT, Smartboard, SQL Plus"),
   ("Inbuilt functions: Numeric", "20 Min", "PPT, Smartboard, SQL Plus"),
   ("Practical 10: Numeric functions - abs, ceil, power, mod, round, trunc, sqrt", "20 Min", "SQL Plus"),
   ("Practical 13: Group functions - avg, min, max, sum, count", "15 Min", "SQL Plus")],
 "exec": "Centralized versus distributed DBMS is explained through two contrasting real systems - a single-branch college ERP versus UPI/IRCTC, which students use daily - and the discussion is driven by the question 'why can IRCTC not run on one server'. Numeric functions are taught as billing-engine building blocks: GST rounding, EMI computation and discount slabs are computed live in SQL so that students see functions solving money problems rather than textbook problems.",
 "sop": [
   "Step 1 (15 min): Revision of previous session; outcome stated - 'student will choose between centralized and distributed architecture for a given business and will perform business calculations using numeric and group functions.'",
   "Step 2 (30 min): Centralized vs distributed DBMS compared on availability, cost, consistency and latency using the college ERP and IRCTC examples; students fill a comparison table.",
   "Step 3 (20 min): Aggregate functions revised and extended - COUNT(DISTINCT), handling of NULL, aggregate with GROUP BY.",
   "Step 4 (20 min): Numeric functions ROUND, TRUNC, MOD, CEIL, FLOOR, ABS, POWER, SQRT demonstrated through a GST and EMI calculation on a live SALES table.",
   "Step 5 (35 min): Students execute Practical 10 and Practical 13; faculty verifies that each student can explain the difference between ROUND and TRUNC with a negative precision example.",
   "Deliverable: A working billing query sheet computing net amount, GST and rounded payable amount, plus completed Practicals 10 and 13."],
 "questions": [
   "An invoice must show amount, 18 percent GST and a final payable value rounded to the nearest rupee. Write a single query that produces all three columns for every row of a SALES table and explain the difference your choice of ROUND versus TRUNC makes to the company over 1 lakh invoices. (Industry problem)",
   "IRCTC handles bookings from the entire country. Explain with two technical reasons why a centralized single-server design would fail, and name the distributed DBMS property that solves each. (Case-based)",
   "Using MOD(), write a query that divides the employees into three equal batches for a training programme, and state how the result changes if an employee is deleted. (Open-book, application-oriented)"],
 "homework": ["On the EMPLOYEE table, write the eight queries using ROUND, MOD, POWER, SQRT, ABS, CEIL, TRUNC, COUNT, SUM, AVG, MIN, MAX and department-wise GROUP BY as listed in the original plan."]
},
{
 "no": 16, "module": "2", "title": "Build DBMS Model - Group Activity (Oracle Architecture 3D Model)",
 "breakdown": [("Divide students into groups of 5-6; each group creates a 3D model, chart or poster of Oracle Database Architecture (Instance, Database, SGA, PGA, Background Processes, Data Files, Control Files, DBA)", "90 Min", "3D Model Creation"),
   ("Teams explain the role of each component as system architects", "30 Min", "Presentation")],
 "exec": "Experiential learning session. Groups of 5-6 build a physical 3D model or poster of the Oracle architecture using chart paper, thermocol and labels. Each member is assigned one component and must defend it as its 'owner' during the presentation. Faculty introduces failure scenarios during the presentation ('your LGWR process has died - explain what happens now') so that the activity tests understanding, not decoration.",
 "sop": [
   "Step 1 (10 min): Groups formed, components allotted member-wise, rubric announced (technical accuracy 40, completeness 20, explanation 30, teamwork 10).",
   "Step 2 (70 min): Model or poster construction; faculty visits each group twice to verify that memory structures and background processes are correctly placed and labelled.",
   "Step 3 (10 min): Groups prepare the narration sequence - data flow of a SELECT and of an INSERT through their model.",
   "Step 4 (25 min): Presentations of 4-5 minutes per group; each member explains his own component; faculty throws one failure scenario at each group.",
   "Step 5 (05 min): Models displayed in the lab, photographs uploaded on ERP, marks recorded.",
   "Deliverable: Physical 3D model or poster, group photograph and a one-page component-wise role note uploaded on ERP."],
 "questions": [
   "Using your model, trace exactly what happens inside the SGA, redo log buffer and data files when a user executes an UPDATE followed by COMMIT. State which process writes to disk first and why. (Senior-level, application)",
   "The LGWR background process of a production database stops responding. Predict the immediate impact on users and on committed transactions, and state the recovery route. (Real-time scenario)",
   "Your group claims the database can run without a control file. Prove or disprove this with reasoning, and state what information the control file uniquely holds. (Analytical, open-book)"],
 "homework": ["Upload model photographs and the component-wise role note; revise architecture for Sessional-I."]
},
{
 "no": 17, "module": "2", "title": "Inbuilt Functions - Date Functions",
 "breakdown": [("Revision", "15 Min", "Discussion"),
   ("Inbuilt functions: Date", "35 Min", "PPT, Smartboard, SQL Plus"),
   ("Practical 9: Date functions - add_months, months_between, round, next_day, trunc", "30 Min", "SQL Plus"),
   ("Practical Assignment-3: Problem solving and practice (Q1-Q10)", "50 Min", "SQL Plus")],
 "exec": "Date functions are taught entirely through HR and banking use cases - probation completion date, retirement date, EMI due dates, number of months of service, next working day for cheque clearance. Faculty first asks students how they would compute each of these manually, then shows the single Oracle function that does it. Emphasis is placed on the industry pain point of date formats (NLS_DATE_FORMAT) because it is the most common cause of production errors.",
 "sop": [
   "Step 1 (15 min): Revision of numeric functions; outcome stated - 'student will solve real HR and banking date problems using Oracle date functions.'",
   "Step 2 (10 min): SYSDATE, date arithmetic and NLS_DATE_FORMAT demonstrated; faculty shows how changing the format mask changes nothing in storage, only in display.",
   "Step 3 (25 min): ADD_MONTHS, MONTHS_BETWEEN, NEXT_DAY, LAST_DAY, ROUND and TRUNC on dates demonstrated, each tied to one HR or banking requirement.",
   "Step 4 (30 min): Practical 9 executed by all students; faculty verifies the output of MONTHS_BETWEEN including the fractional part and asks each bench to interpret it.",
   "Step 5 (50 min): Assignment-3 Q1-Q10 solved individually; faculty resolves doubts and gives a mid-way correction talk.",
   "Deliverable: An HR query sheet producing probation end date, completed service in months and retirement date for every employee."],
 "questions": [
   "An HR policy states that probation ends exactly 6 months after joining and that the confirmation letter must be issued on the next Monday after that date. Write a single query producing employee name, probation end date and letter issue date. (Industry problem)",
   "A bank must list all loan accounts whose EMI is due on the last day of the current month and must also show the number of completed months since disbursement. Write the query and explain which function handles month-end correctly for February. (Case-based)",
   "Two queries on the same table give different results: one uses TRUNC(join_date) and the other does not. Explain with an example why the time component causes this and state the correct practice for date comparison. (Open-book, senior-level)"],
 "homework": ["Write the four queries using ADD_MONTHS, MONTHS_BETWEEN, NEXT_DAY, ROUND and TRUNC on employee joining dates as listed in the original plan."]
},
{
 "no": 18, "module": "2", "title": "Inbuilt Functions - String Functions",
 "breakdown": [("Revision", "15 Min", "Discussion"),
   ("Inbuilt functions: String", "30 Min", "PPT, Smartboard, SQL Plus"),
   ("Practical 11: String functions - initcap, lower, upper, rtrim, replace, substr, instr", "35 Min", "SQL Plus"),
   ("Practical Assignment-3: Problem solving and practice (Q11-Q25)", "40 Min", "SQL Plus")],
 "exec": "Executed as a data-cleaning workshop, which is exactly how string functions are used in industry. Faculty supplies a deliberately dirty dataset (names in mixed case with trailing spaces, phone numbers with +91 and dashes, email ids in capitals, addresses with double spaces) and students must clean it using string functions only. This converts a routine syntax topic into a real data-quality task and prepares students for case-based examination questions.",
 "sop": [
   "Step 1 (15 min): Revision of date functions; faculty loads the dirty dataset script on all machines; outcome stated - 'student will clean and standardise real dirty data using Oracle string functions.'",
   "Step 2 (30 min): UPPER, LOWER, INITCAP, LENGTH, LTRIM, RTRIM, TRIM, SUBSTR, INSTR, REPLACE, CONCAT and LPAD demonstrated, each applied to one dirty column of the dataset.",
   "Step 3 (35 min): Practical 11 executed; students must produce a fully cleaned output of the dataset and get it verified.",
   "Step 4 (40 min): Assignment-3 Q11-Q25 solved; faculty picks two tricky questions and solves them on the smartboard after students attempt them.",
   "Deliverable: Before-and-after cleaned dataset output pasted in the lab file with the query used for each column."],
 "questions": [
   "A marketing database has names stored as '  rAHUL   patel ' and mobile numbers as '+91-98250-11223'. Write queries to produce a properly capitalised name without extra spaces and a clean 10-digit mobile number. (Real-life data cleaning)",
   "From an email column, extract the username part and the domain part as two separate columns, and then count how many customers use gmail. Write all queries. (Industry-oriented, application)",
   "Explain why LENGTH('RAHUL ') and LENGTH(TRIM('RAHUL ')) return different values and describe one real bug in a login system that this difference can cause. (Open-book, analytical)"],
 "homework": ["Write the four queries using UPPER, LOWER, INITCAP, SUBSTR, INSTR, RTRIM and REPLACE on employee names and departments as listed in the original plan."]
},
]
